#!/usr/bin/env python3
"""Emit the module-side SessionBindKey.h from a keydir's heartbeat.key.

Format matches the machine-local file the dev workflow keeps in
cs2/Source/Utils/SessionBindKey.h and tf2/Source/SessionBindKey.h:
kKeyMasked = heartbeat.key XOR kKeyMask, with a fresh random mask per generation.

The unmasked key must equal the loader's heartbeat.key (the loader stamps a
comm XOR key trailer that the module verifies fail-closed). Both sides read the
same shared keydir, so they stay in sync by construction.

usage: gen_session_bind_key.py <heartbeat.key> <out-header>
"""
import secrets
import sys


def rows(data: bytes) -> str:
    return ",\n".join(
        "    " + ", ".join(f"0x{b:02X}" for b in data[i : i + 8])
        for i in range(0, len(data), 8)
    )


key = open(sys.argv[1], "rb").read()
if len(key) != 32:
    sys.exit(f"heartbeat key must be 32 bytes, got {len(key)}")
mask = secrets.token_bytes(32)
masked = bytes(k ^ m for k, m in zip(key, mask))

header = f"""#pragma once

// Session bind key material - split into two masked parts for anti-static-analysis.
// The actual key is kKeyMasked[i] ^ kKeyMask[i].
// Generated by the Nix key-material derivation (heartbeat.key XOR a fresh random mask).
// This MUST match the heartbeat keys in neversneeze-loader's payload_keys.h - both
// sides read the same shared keydir, so they stay in sync by construction.
namespace session_bind_key
{{

constexpr unsigned char kKeyMasked[32] = {{
{rows(masked)}
}};

constexpr unsigned char kKeyMask[32] = {{
{rows(mask)}
}};

}} // namespace session_bind_key
"""
with open(sys.argv[2], "w") as f:
    f.write(header)
print(f"wrote {sys.argv[2]}")
