#pragma once

#include <Features/Combat/Aimbot/AimbotConfigVariables.h>
#include <Features/Combat/LegitAimbot/LegitAimbotConfigVariables.h>
#include <Features/Combat/Rcs/RcsConfigVariables.h>
#include <Features/Combat/SpreadCircleVis/SpreadCircleVisConfigVariables.h>
#include <Features/Radio/RadioConfigVariables.h>
#include <Features/Combat/SniperRifles/NoScopeInaccuracyVis/NoScopeInaccuracyVisConfigVariables.h>
#include <Features/Combat/Triggerbot/TriggerbotConfigVariables.h>
#include <Features/Game/BlockbotConfigVariables.h>
#include <Features/Game/BunnyhopConfigVariables.h>
#include <Features/Game/CooldownRevealerConfigVariables.h>
#include <Features/Game/FakeLevelConfigVariables.h>
#include <Features/Game/MovementConfigVariables.h>
#include <Features/Hud/SpectatorList/SpectatorListParams.h>
#include <Features/Game/FakePrimeConfigVariables.h>
#include <Features/Game/FvaConfigVariables.h>
#include <Features/Game/MatchAutoAcceptConfigVariables.h>
#include <Features/Game/HitLogConfigVariables.h>
#include <Features/Game/KillsayConfigVariables.h>
#include <Features/Game/ValveDsSpoofConfigVariables.h>
#include <Features/Game/PanicKeyConfigVariables.h>
#include <Features/Game/TeamDamageConfigVariables.h>
#include <Features/Hud/HudThemeColorConfigVariables.h>
#include <Features/Misc/DiscordRpcConfigVariables.h>
#include <Features/Game/VoteRevealerConfigVariables.h>
#include <Features/Hud/BombPlantAlert/BombPlantAlertConfigVariables.h>
#include <Features/Hud/BindsList/BindsListConfigVariables.h>
#include <Features/Hud/BombTimer/BombTimerConfigVariables.h>
#include <Features/Hud/DefusingAlert/DefusingAlertConfigVariables.h>
#include <Features/Hud/KillfeedPreserver/KillfeedPreserverConfigVariables.h>
#include <Features/Hud/PostRoundTimer/PostRoundTimerConfigVariables.h>
#include <Features/Hud/Watermark/WatermarkConfigVariables.h>
#include <Features/SkinChanger/SkinChangerConfigVariables.h>
#include <Features/Sound/HitSoundConfigVariables.h>
#include <Features/Sound/SoundVisualizationConfigVariables.h>
#include <Features/Sound/SpawnProtectionSoundConfigVariables.h>
#include <Features/Visuals/GrenadeTimers/GrenadeTimersConfigVariables.h>
#include <Features/Visuals/Hitmarker/HitmarkerConfigVariables.h>
#include <Features/Visuals/ModelGlow/ModelGlowConfigVariables.h>
#include <Features/Visuals/OutlineGlow/OutlineGlowConfigVariables.h>
#include <Features/Visuals/PlayerInfoInWorld/PlayerInfoInWorldConfigVariables.h>
#include <Features/Visuals/PlayerList/PlayerListConfigVariables.h>
#include <Features/Visuals/Removals/RemovalsConfigVariables.h>
#include <Features/Visuals/ThirdPerson/ThirdPersonConfigVariables.h>
#include <Features/Visuals/ViewmodelMod/ViewmodelModConfigVariables.h>
#include <Features/Visuals/WorldColors/WorldColorsConfigVariables.h>
#include <UI/ImGui/Neverlose/MenuThemeConfigVariables.h>
#include <Utils/TypeList.h>

using ConfigVariableTypes = TypeList<
    BombTimerEnabled,
    watermark_vars::Enabled,
    DefusingAlertEnabled,
    KillfeedPreserverEnabled,
    PostRoundTimerEnabled,
    BombBeepSoundVisualizationEnabled,
    BombDefuseSoundVisualizationEnabled,
    HitSoundEnabled,
    radio_vars::Volume,
    SpawnProtectionSoundEnabled,
    HitLogEnabled,
    KillsayEnabled,
    TeamDamageTrackerEnabled,
    VoteRevealerEnabled,
    CooldownRevealerEnabled,
    BlockbotEnabled,
    BunnyhopEnabled,
    AutoStrafeEnabled,
    TestStraferEnabled,
    panic_vars::Bind,
    FakePrimeEnabled,
    FakeLevelEnabled,
    FakeLevelValue,
    MatchAutoAcceptEnabled,
    BombPlantSoundVisualizationEnabled,
    FootstepSoundVisualizationEnabled,
    WeaponReloadSoundVisualizationEnabled,
    WeaponScopeSoundVisualizationEnabled,
    model_glow_vars::Enabled,
    model_glow_vars::GlowPlayers,
    model_glow_vars::GlowOnlyEnemies,
    model_glow_vars::GlowWeapons,
    model_glow_vars::GlowDroppedBomb,
    model_glow_vars::GlowTickingBomb,
    model_glow_vars::GlowDefuseKits,
    model_glow_vars::GlowGrenadeProjectiles,
    model_glow_vars::AllyColor,
    model_glow_vars::EnemyColor,
    model_glow_vars::MolotovHue,
    model_glow_vars::FlashbangHue,
    model_glow_vars::HEGrenadeHue,
    model_glow_vars::SmokeGrenadeHue,
    model_glow_vars::DroppedBombHue,
    model_glow_vars::TickingBombHue,
    model_glow_vars::DefuseKitHue,
    outline_glow_vars::Enabled,
    outline_glow_vars::GlowDefuseKits,
    outline_glow_vars::GlowDroppedBomb,
    outline_glow_vars::GlowGrenadeProjectiles,
    outline_glow_vars::GlowHostages,
    outline_glow_vars::GlowPlayers,
    outline_glow_vars::GlowOnlyEnemies,
    outline_glow_vars::GlowTickingBomb,
    outline_glow_vars::GlowWeapons,
    outline_glow_vars::AllyColor,
    outline_glow_vars::EnemyColor,
    outline_glow_vars::MolotovHue,
    outline_glow_vars::FlashbangHue,
    outline_glow_vars::HEGrenadeHue,
    outline_glow_vars::SmokeGrenadeHue,
    outline_glow_vars::DroppedBombHue,
    outline_glow_vars::TickingBombHue,
    outline_glow_vars::DefuseKitHue,
    outline_glow_vars::HostageHue,
    player_info_vars::Enabled,
    player_info_vars::OnlyEnemies,
    player_info_vars::PlayerPositionArrowEnabled,
    player_info_vars::PlayerPositionArrowColorMode,
    player_info_vars::PlayerHealthEnabled,
    player_info_vars::PlayerHealthColorMode,
    player_info_vars::ActiveWeaponIconEnabled,
    player_info_vars::ActiveWeaponAmmoEnabled,
    player_info_vars::BombCarrierIconEnabled,
    player_info_vars::BombPlantIconEnabled,
    player_info_vars::BombDefuseIconEnabled,
    player_info_vars::HostagePickupIconEnabled,
    player_info_vars::HostageRescueIconEnabled,
    player_info_vars::BlindedIconEnabled,
    viewmodel_mod_vars::ModifyFov,
    viewmodel_mod_vars::ModifyPosition,
    viewmodel_mod_vars::OffsetX,
    viewmodel_mod_vars::OffsetY,
    viewmodel_mod_vars::OffsetZ,
    viewmodel_mod_vars::Fov,
    no_scope_inaccuracy_vis_vars::Enabled,
    triggerbot_vars::Enabled,
    triggerbot_vars::HoldKey,
    triggerbot_vars::DelayMilliseconds,
    triggerbot_vars::DelayMillisecondsMax,
    triggerbot_vars::AccuracyCheck,
    triggerbot_vars::AccuracyRadius,
    triggerbot_vars::HeadOnly,
    triggerbot_vars::Hitchance,
    triggerbot_vars::MaxAccuracyOnly,
    triggerbot_vars::WallCheck,
    triggerbot_vars::Autowall,
    triggerbot_vars::AutowallMaxThickness,
    triggerbot_vars::SpreadCompensation,
    triggerbot_vars::SeededFire,
    aimbot_vars::Enabled,
    aimbot_vars::HitHead,
    aimbot_vars::HitChest,
    aimbot_vars::HitStomach,
    aimbot_vars::HitArms,
    aimbot_vars::HitLegs,
    aimbot_vars::SpreadCompensation,
    aimbot_vars::RecoilCompensation,
    aimbot_vars::ForceShot,
    aimbot_vars::ForceShotAir,
    aimbot_vars::Extrapolate,
    aimbot_vars::ExtrapolateTicks,
    aimbot_vars::BodyAim,
    aimbot_vars::Hitchance,
    aimbot_vars::MinDamage,
    aimbot_vars::Multipoint,
    aimbot_vars::Backtrack,
    aimbot_vars::BacktrackTicks,
    aimbot_vars::SpreadCircleFov,
    aimbot_vars::AutoStop,
    aimbot_vars::PointScale,
    aimbot_vars::DynamicPointscale,
    aimbot_vars::WallCheck,
    aimbot_vars::Autowall,
    aimbot_vars::SpreadGate,
    aimbot_vars::SeedFallback,
    movement_vars::EdgeJump,
    movement_vars::EdgeStop,
    movement_vars::SlowWalk,
    movement_vars::SlowWalkSpeed,
    movement_vars::FastLadder,
    movement_vars::JumpBug,
    spectator_list_params::SpectatorListEnabled,
    PlayerListOffsetX,
    PlayerListOffsetY,
    legit_aimbot_vars::Enabled,
    legit_aimbot_vars::AimKey,
    legit_aimbot_vars::Fov,
    legit_aimbot_vars::Smooth,
    legit_aimbot_vars::DrawFov,
    legit_aimbot_vars::FovCircleColor,
    legit_aimbot_vars::HitHead,
    legit_aimbot_vars::HitChest,
    legit_aimbot_vars::HitStomach,
    legit_aimbot_vars::HitArms,
    legit_aimbot_vars::HitLegs,
    legit_aimbot_vars::SpreadCircleFov,
    spread_circle_vars::Enabled,
    spread_circle_vars::SpreadCircleColor,
    rcs_vars::Enabled,
    rcs_vars::Strength,
    BombPlantAlertEnabled,
    skin_changer_vars::KnifeModel,
    skin_changer_vars::KnifeSkin,
    skin_changer_vars::M4A4Skin,
    skin_changer_vars::AK47Skin,
    skin_changer_vars::AWPSkin,
    skin_changer_vars::DesertEagleSkin,
    skin_changer_vars::USPSSkin,
    skin_changer_vars::Glock18Skin,
    skin_changer_vars::M249Skin,
    skin_changer_vars::XM1014Skin,
    skin_changer_vars::MAG7Skin,
    skin_changer_vars::NegevSkin,
    skin_changer_vars::SawedOffSkin,
    skin_changer_vars::NovaSkin,
    skin_changer_vars::DualBerettasSkin,
    skin_changer_vars::FiveSeveNSkin,
    skin_changer_vars::Tec9Skin,
    skin_changer_vars::P2000Skin,
    skin_changer_vars::P250Skin,
    skin_changer_vars::CZ75AutoSkin,
    skin_changer_vars::R8RevolverSkin,
    skin_changer_vars::AUGSkin,
    skin_changer_vars::FamasSkin,
    skin_changer_vars::GalilARSkin,
    skin_changer_vars::SG553Skin,
    skin_changer_vars::M4A1SSkin,
    skin_changer_vars::MAC10Skin,
    skin_changer_vars::P90Skin,
    skin_changer_vars::MP5SDSkin,
    skin_changer_vars::UMP45Skin,
    skin_changer_vars::PPBizonSkin,
    skin_changer_vars::MP7Skin,
    skin_changer_vars::MP9Skin,
    skin_changer_vars::G3SG1Skin,
    skin_changer_vars::SCAR20Skin,
    skin_changer_vars::SSG08Skin,
    FvaEnabled,
    FvaZeroOriginSpoof,
    fva_vars::Substeps,
    FvaReseedChains,
    FvaChainOnFireOnly,
    ValveDsSpoofEnabled,
    FvaSilentShots,
    HitmarkerEnabled,
    HitmarkerLength,
    HitmarkerGap,
    HitmarkerTimeout,
    HitmarkerColor,
    ForceThirdPersonEnabled,
    ForceThirdPersonDistance,
    RemoveViewPunch,
    RemoveLegs,
    RemoveFlashOverlay,
    RemoveMenuAds,
    WorldColorsInfernoEnabled,
    MolotovColor,
    IncendiaryColor,
    WorldColorsLightsEnabled,
    WorldColorsLightColor,
    WorldColorsSkyEnabled,
    WorldColorsSkyColor,
    WorldColorsWorldEnabled,
    WorldColorsWorldColor,
    WorldColorsFogEnabled,
    WorldColorsFogColor,
    WorldColorsFogDensity,
    WorldColorsFogDistance,
    WorldColorsBloomEnabled,
    WorldColorsBloomStrength,
    WorldColorsSkyBrightness,
    PlayerListEnabled,
    MenuAccentColor,
    MenuButtonColor,
    MenuSliderColor,
    MenuGlowEnabled,
    MenuGlowColor,
    MenuGlowRainbow,
    MenuGlowSpeed,
    MenuGlowSize,
    MenuGlowDebug,
    watermark_vars::ShowFps,
    watermark_vars::ShowSpeed,
    watermark_vars::ShowPing,
    watermark_vars::ShowTeamDamage,
    watermark_vars::ShowClock,
    watermark_vars::OffsetX,
    watermark_vars::OffsetY,
    binds_list_vars::Enabled,
    grenade_timers_vars::Enabled,
    grenade_timers_vars::SmokeTimers,
    grenade_timers_vars::MolotovTimers,
    radio_vars::MicBroadcast,
    MenuStyleRainbow,
    discord_rpc_vars::Enabled,
    hud_theme_vars::Enabled
>;
