#pragma once

#include <atomic>
#include <optional>
#include <cstddef>
#include <cstdio>
#include <cstring>

#include <fcntl.h>
#include <unistd.h>

#include <CS2/Classes/IGameEventManager2.h>
#include <CS2/Econ/ItemDefDatabase.h>
#include <GameClient/ConVars/CvarSystem.h>
#include <GameClient/EntitySystem/EntitySystem.h>
#include <CS2/Constants/DllNames.h>
#include <Features/Game/ChatToolsConfigVariables.h>
#include <Features/Hud/SpectatorList/SpectatorSnapshot.h>
#include <Features/Visuals/PlayerList/PlayerListSnapshot.h>
#include <GameClient/Bind.h>
#include <GameClient/EngineCommandExecutor.h>
#include <GameClient/GameEvents/GameEventFields.h>
#include <Platform/DynamicLibrary.h>
#include <HookContext/HookContextMacros.h>
#include <Platform/Linux/LinuxPlatformApi.h>
#include <Utils/CrashLogger.h>
#include <Utils/VerifyConsole.h>

// Chat tools - every piece of this is genuinely networked, exactly like Killsay:
//
//   Fake Name   - rewrites the userinfo `name` convar, so chat lines, killfeed, scoreboard and
//                 the lobby ALL show the new name to every player on the server. This is the
//                 closest possible "VAC Live"-style trick: name yourself e.g.
//                 "VAC Live [VALVe]" or "Krypt0n [VAC banned from secure server]" and every
//                 chat line you send reads like a system message. (The one thing that cannot
//                 be faked networked is the real [VALVe] BADGE styling - that is client-side
//                 decoration from Steam account flags on every other client. Same for the
//                 actual "X disconnected [VAC banned]" lines: they are generated by the SERVER
//                 via the player_disconnect event on every client, a client cannot inject one.)
//   Chat Spam   - burst-floods `say` with the spam line (chat "clearing"). Burst count +
//                 interval are config vars; after each burst there is a 3s cooldown so a
//                 careless toggle does not instantly trip the server's spam kick.
//   Radio Spam  - `playerchatwheel cmd "<text>"` - the chat wheel voice line, networked to
//                 everyone (the format string `playerchatwheel %s "%s"` is in libclient).
//   Fast Colors - rapid `cl_hud_color 0..11` cycling (menu + in-game HUD accent flashing).
//
// Text sources: sidecar files next to the configs, one line each (the config schema has no
// string type - same pattern as killsay.txt / discord_rpc.txt). The menu edits static buffers
// (present thread) that flush to the sidecars on deactivate; the game thread re-reads the
// files when it sends, so edits apply live. EVERY text is sanitized before it reaches the
// console: quotes, semicolons and control bytes would be command injection.
//
// Threading: run() is called from CreateMove AND FrameStageNotify 6 (InventoryChanger
// precedent) so the timers tick in the main menu too; the shared per-subsystem tick state
// makes the double caller idempotent. The menu's APPLY button only publishes an atomic.
namespace chat_tools
{

// Strips every byte that could break out of a console command: quotes, semicolons, control
// bytes. ALSO converts the {nl} and "\n" escapes into U+2028 (Unicode LINE SEPARATOR): the
// Panorama chat renders it as a real line break while it is NOT a control byte - so it passes
// through the console parser AND the server's name/message validation untouched. This is what
// makes the multi-line persona names work networked (fake system-message blocks in chat).
inline std::size_t sanitizeInto(const char* in, char* out, std::size_t outCapacity) noexcept
{
    constexpr char kLineSeparator[] = "\xE2\x80\xA8"; // U+2028
    std::size_t writeIndex = 0;
    for (std::size_t i = 0; in[i] != '\0' && writeIndex + 4 < outCapacity; ++i) {
        const auto c = in[i];
        if (c == '{' && std::strncmp(in + i, "{nl}", 4) == 0) {
            std::memcpy(out + writeIndex, kLineSeparator, 3);
            writeIndex += 3;
            i += 3;
            continue;
        }
        if (c == '\\' && in[i + 1] == 'n') {
            std::memcpy(out + writeIndex, kLineSeparator, 3);
            writeIndex += 3;
            ++i;
            continue;
        }
        if (c == '"' || c == ';' || static_cast<unsigned char>(c) < 0x20 || c == 0x7F)
            continue;
        out[writeIndex++] = c;
    }
    out[writeIndex] = '\0';
    return writeIndex;
}

// Case-insensitive ASCII compare (the wheel/CW name resolution needs it).
[[nodiscard]] inline bool equalsIgnoreCase(const char* a, const char* b) noexcept
{
    for (int i = 0; a[i] != '\0' || b[i] != '\0'; ++i) {
        char ca = a[i];
        char cb = b[i];
        if (ca >= 'A' && ca <= 'Z')
            ca += 32;
        if (cb >= 'A' && cb <= 'Z')
            cb += 32;
        if (ca != cb)
            return false;
        if (ca == '\0')
            return true;
    }
    return true;
}

// one-shot request from the menu (present thread), consumed by run() on the game thread
inline std::atomic<int> pendingNameApply{0};

// run() has TWO callers per in-game frame (CreateMove + FrameStageNotify 6); this counter lets
// exactly one of them drive the cadence so intervals/colors run at their labeled rate.
inline std::atomic<int> callerParity{0};

// cadence state - inline statics, NOT class members: hookContext.make<ChatTools>() constructs a
// temporary per call, so member state would reset every tick (same reason InventoryChanger
// keeps its throttle in the namespace).
inline int spamTicksLeft = 0;
inline int spamLinesLeft = 0;
inline int spamCooldownLeft = 0;
inline int wheelTicksLeft = 0;
inline int colorTicksLeft = 0;
inline int colorIndex = 0;

// name cycler (chat_names.txt)
inline const char* const kNamesListFile = "/chat_names.txt";
inline int cycleIndex = 0;
inline int cycleCount = 0;
inline int cycleTicksLeft = 0;

// fake kick key edge + burst
inline bool kickWasDown = false;
inline int kickSendCooldown = 0;
inline int kickAttemptsRemaining = 0;

// fake intel
inline bool intelWasEnabled = false;
inline bool intelWasDown = false;
inline int intelSendCooldown = 0;

// killstreak radio
inline int streak = 0;

// spectator live reaction
inline int lastSpectatorCount = 0;
inline int liveSayCooldown = 0;

// the "Server" persona the fake intel mode wears (badge-lookalike tail, networked)
inline constexpr const char* kServerPersona = "Server \xE2\x81\xA7\xE2\x81\xA7[V\xCE\x91LV\xE1\xB4\xB1]";

// --- radio phrases (chat wheel) --------------------------------------------------------
//
// The 21 chat-wheel phrases as ItemDefEntry entries so the menu's searchable/scrollable
// picker machinery works unchanged (defIndex = the dropdown index). The server command is
// `playerchatwheel CW.<name> CW.<name>` - USER-CONFIRMED working: chat line + VOICE for
// everyone. cwName carries the exact CW.X the server validates against its own table.
struct RadioPhraseEntry {
    std::uint8_t index;
    const char* cwName;
    const char* display;
};
inline constexpr RadioPhraseEntry kRadioPhrases[] = {
    {0, "CW.EcoRound", "Eco round"},
    {1, "CW.SpendRound", "Spend round"},
    {2, "CW.NeedDrop", "Need a drop"},
    {3, "CW.NeedPlan", "Need a plan"},
    {4, "CW.NeedLeader", "Need a leader"},
    {5, "CW.GoGoGo", "Go go go!"},
    {6, "CW.OMW", "On my way"},
    {7, "CW.FollowMe", "Follow me"},
    {8, "CW.FollowingYou", "Following you"},
    {9, "CW.GoA", "Go to A"},
    {10, "CW.GoB", "Go to B"},
    {11, "CW.GoToLocMid", "Go to mid"},
    {12, "CW.Regroup", "Regroup"},
    {13, "CW.StickTogether", "Stick together"},
    {14, "CW.SpreadOut", "Spread out"},
    {15, "CW.TeamFallBack", "Team fall back"},
    {16, "CW.HoldPosition", "Hold this position"},
    {17, "CW.NeedQuiet", "Need quiet"},
    {18, "CW.ImAttacking", "I'm attacking"},
    {19, "CW.HeardNoise", "Heard noise"},
    {20, "CW.SeesEnemy", "Enemy spotted"},
};
inline constexpr int kRadioPhraseCount = static_cast<int>(sizeof(kRadioPhrases) / sizeof(kRadioPhrases[0]));

// The cs2::ItemDefEntry-shaped mirror for the menu's picker machinery. defIndex is 1-BASED:
// 0 is reserved by the picker's virtual "None" row (and would collide with its PushID).
inline constexpr cs2::ItemDefEntry kWheelRadioEntries[kRadioPhraseCount] = {
    {1, "Eco round", ""}, {2, "Spend round", ""}, {3, "Need a drop", ""},
    {4, "Need a plan", ""}, {5, "Need a leader", ""}, {6, "Go go go!", ""},
    {7, "On my way", ""}, {8, "Follow me", ""}, {9, "Following you", ""},
    {10, "Go to A", ""}, {11, "Go to B", ""}, {12, "Go to mid", ""},
    {13, "Regroup", ""}, {14, "Stick together", ""}, {15, "Spread out", ""},
    {16, "Team fall back", ""}, {17, "Hold this position", ""}, {18, "Need quiet", ""},
    {19, "I'm attacking", ""}, {20, "Heard noise", ""}, {21, "Enemy spotted", ""},
};

// --- fake kick (networked "Invalid Steam Logon" / reason kick) -------------------------
//
// The engine interface Source2EngineToClient001::CmdKeyValues (vtable byte offset 0x3B8 =
// slot 119) forwards a KeyValues message to the server; sending KV name "InvalidSteamLogon"
// with an int "reason" makes the SERVER kick us with that reason ("Invalid Steam Logon
// Delayed: Kicking client [U:1:%d] %s" in the server log) - a REAL disconnect line every
// player sees. Ported from a friend's Windows PoC; every KeyValues method is dlsym-able from
// libtier0 by mangled name (update-proof, no RVAs), the interface comes from engine2's
// exported CreateInterface. The Linux vtable slot was confirmed identical to Windows
// (multiple `call *0x3b8` sites through the engine global at libclient+0x4821138, the
// game's own CrosshairCode sender at +0x14fcd20 uses the same construction sequence).
//
// The burst (one send per frame for ~180 frames) exists because the server only stores the
// delayed-kick reason in a specific client-state window. Dispatch must run on the game
// thread (the net channel/KV path is not thread-safe) - our run() already is.
//
// OWNERSHIP: the engine takes the KV (the game's own sender does NOT free after dispatch) -
// do NOT delete after sending.
inline void* engineInterface = nullptr;
inline bool kickSymbolsResolved = false;

using KVNewFn = void* (*)(std::size_t);
using KVCtorFn = void* (*)(void*, const char*, void*, bool);
using KVSetIntFn = void (*)(void*, const char*, int);
using CreateInterfaceFn = void* (*)(const char*, int*);
using DispatchFn = void (*)(void*, void*);

inline KVNewFn kvNew = nullptr;
inline KVCtorFn kvCtor = nullptr;
inline KVSetIntFn kvSetInt = nullptr;
inline DispatchFn cmdKeyValues = nullptr;

inline bool resolveKickSymbols() noexcept
{
    if (kickSymbolsResolved)
        return engineInterface && cmdKeyValues;

    kickSymbolsResolved = true;
    DynamicLibrary tier0{cs2::TIER0_DLL};
    kvNew = tier0.getFunctionAddress("_ZN9KeyValuesnwEm").as<KVNewFn>();
    kvCtor = tier0.getFunctionAddress("_ZN9KeyValuesC1EPKcP16IKeyValuesSystemb").as<KVCtorFn>();
    kvSetInt = tier0.getFunctionAddress("_ZN9KeyValues6SetIntEPKci").as<KVSetIntFn>();
    if (!kvNew || !kvCtor || !kvSetInt)
        return false;

    DynamicLibrary engine2{cs2::ENGINE_DLL};
    const auto createInterface = engine2.getFunctionAddress("CreateInterface").as<CreateInterfaceFn>();
    if (!createInterface)
        return false;
    engineInterface = createInterface("Source2EngineToClient001", nullptr);
    if (!engineInterface)
        return false;

    const auto vtable = *reinterpret_cast<void***>(engineInterface);
    cmdKeyValues = reinterpret_cast<DispatchFn>(vtable[0x3B8 / 8]);
    return cmdKeyValues != nullptr;
}

// One send attempt; silent no-op while the symbols/interface are unavailable.
inline void sendInvalidSteamLogon(int reason) noexcept
{
    if (!resolveKickSymbols())
        return;
    void* kv = kvNew(0x1C);
    if (kv)
        kvCtor(kv, "InvalidSteamLogon", nullptr, false);
    kvSetInt(kv, "reason", reason);
    cmdKeyValues(engineInterface, kv);
    // the engine owns the KV (the game's own CrosshairCode sender never frees) - no delete
}

inline int kickBurstRemaining = 0;

// --- Steam persona name (the REAL name change) ------------------------------------------
//
// CS2 takes the in-game name from the STEAM persona (the `name` convar alone gets overridden
// by the GC), so changing the name = ISteamFriends::SetPersonaName - which is exactly how
// multi-line persona names exist at all (U+2028 line separators live in the Steam profile
// name and every server/chat renders them).
//
// Interface: SteamFriends017 (the exact version the game requests) via
// SteamInternal_FindOrCreateUserInterface(SteamAPI_GetHSteamUser(), "SteamFriends017") -
// both exported from libsteam_api.so. ISteamFriends has no virtual destructor, so the
// vtable is [0]=GetPersonaName, [1]=SetPersonaName (same on Itanium - verified against the
// public SDK header order). We sanity-check slot 0 against the persona file the account bar
// already fetched before trusting slot 1.
//
// CAVEATS: Steam rate-limits persona changes (~1/min) and the change is PUBLIC on the
// profile (it persists after the game closes) - that is the price of the friend's trick.
constexpr std::size_t kBufferTextSize2 = 160;

inline void* steamFriends = nullptr;
inline bool personaSymbolsResolved = false;

inline char personaRequested[kBufferTextSize2] = "";
inline int personaPollsLeft = 0;

using GetHSteamUserFn = int (*)();
using FindOrCreateUserInterfaceFn = void* (*)(int, const char*);
using GetPersonaNameFn = const char* (*)(void*);
using SetPersonaNameFn = bool (*)(void*, const char*);

inline bool resolvePersonaSymbols() noexcept
{
    if (personaSymbolsResolved)
        return steamFriends != nullptr;
    personaSymbolsResolved = true;

    VerifyConsole::write(0.0f, "persona", "resolving steam interface...");

    // Locate the ACTUAL loaded libsteam_api from our own /proc/self/maps. Chunked read with
    // a carry-over line buffer (lines split across pread boundaries are common) - the first
    // version of this scan dropped split lines and had an off-by-two suffix check, so it
    // NEVER matched even though the library is loaded.
    char steamApiPath[512] = "";
    {
        const int fd = LinuxPlatformApi::open("/proc/self/maps", 0 /* O_RDONLY */);
        if (fd >= 0) {
            constexpr std::size_t kCarry = 1024;
            char chunk[4096];
            char carry[kCarry];
            std::size_t carryLength = 0;
            off_t position = 0;
            bool found = false;
            while (!found) {
                const auto got = LinuxPlatformApi::pread(fd, chunk, sizeof(chunk), position);
                if (got <= 0)
                    break;
                position += static_cast<off_t>(got);

                std::size_t lineBegin = 0;
                for (std::size_t i = 0; i < static_cast<std::size_t>(got); ++i) {
                    if (chunk[i] != '\n')
                        continue;
                    char line[kCarry + 4096];
                    std::size_t lineLength = 0;
                    if (carryLength > 0) {
                        std::memcpy(line, carry, carryLength);
                        lineLength = carryLength;
                    }
                    const auto part = (i - lineBegin) < (sizeof(line) - lineLength - 1) ? (i - lineBegin) : (sizeof(line) - lineLength - 1);
                    std::memcpy(line + lineLength, chunk + lineBegin, part);
                    lineLength += part;
                    line[lineLength] = '\0';
                    carryLength = 0;

                    // path = the first '/' in the line - the five numeric fields before it
                    // (addr-perms-offset-dev-inode) never contain slashes. "After the last
                    // space" was WRONG: Steam library paths contain spaces
                    // ("Counter-Strike Global Offensive") and got chopped mid-path.
                    const char* path = line;
                    for (std::size_t j = 0; j < lineLength; ++j) {
                        if (line[j] == '/') {
                            path = line + j;
                            break;
                        }
                    }
                    if (std::strstr(path, "libsteam_api.so")) {
                        const auto rest = std::strlen(path);
                        std::memcpy(steamApiPath, path, rest < sizeof(steamApiPath) - 1 ? rest : sizeof(steamApiPath) - 1);
                        steamApiPath[rest < sizeof(steamApiPath) - 1 ? rest : sizeof(steamApiPath) - 1] = '\0';
                        found = true;
                        break;
                    }
                    lineBegin = i + 1;
                }

                if (found)
                    break;
                // carry the trailing partial line into the next chunk
                carryLength = 0;
                const std::size_t remaining = static_cast<std::size_t>(got) - lineBegin;
                if (remaining > 0 && remaining < kCarry) {
                    std::memcpy(carry, chunk + lineBegin, remaining);
                    carryLength = remaining;
                } else if (remaining >= kCarry) {
                    carryLength = 0; // pathological line - skip it rather than overflow
                }
            }
            LinuxPlatformApi::close(fd);
        }
    }
    if (steamApiPath[0] == '\0') {
        VerifyConsole::write(0.0f, "persona", "libsteam_api.so NOT in our maps - interface unavailable");
        return false;
    }
    VerifyConsole::write(0.0f, "persona", "steam_api at %s", steamApiPath);

    DynamicLibrary steamApi{steamApiPath};
    const auto getHUser = steamApi.getFunctionAddress("SteamAPI_GetHSteamUser").as<GetHSteamUserFn>();
    const auto findInterface = steamApi.getFunctionAddress("SteamInternal_FindOrCreateUserInterface").as<FindOrCreateUserInterfaceFn>();
    if (!getHUser || !findInterface) {
        VerifyConsole::write(0.0f, "persona", "steam_api exports missing");
        return false;
    }
    const int user = getHUser();
    steamFriends = findInterface(user, "SteamFriends017");
    if (!steamFriends) {
        VerifyConsole::write(0.0f, "persona", "SteamFriends017 unavailable (user %d)", user);
        return false;
    }
    VerifyConsole::write(0.0f, "persona", "SteamFriends017 ok");
    return true;
}

// Sets the Steam persona name. Returns false when the interface is unavailable.
//
// THE +0x8 INDIRECTION (friend's fix, 2026-09-07): SteamFriends017 obtained through
// CreateInterface is a WRAPPER - calling vtable slots on it directly never actually renamed
// (the wrapper's slot 1 is not SetPersonaName). The REAL ISteamFriends object sits at +0x8 in
// the wrapper; slots 0/1 of THAT vtable are GetPersonaName/SetPersonaName. This is the same
// pattern every working CS2 name changer uses.
inline bool setSteamPersonaName(const char* name) noexcept
{
    if (!name || !resolvePersonaSymbols())
        return false;
    void* internal = *reinterpret_cast<void**>(reinterpret_cast<std::uintptr_t>(steamFriends) + 0x8);
    if (!internal) {
        VerifyConsole::write(0.0f, "persona", "wrapper +0x8 is null - unexpected interface layout");
        return false;
    }
    const auto vtable = *reinterpret_cast<void***>(internal);
    const auto getPersonaName = reinterpret_cast<GetPersonaNameFn>(vtable[0]);
    const auto setPersonaName = reinterpret_cast<SetPersonaNameFn>(vtable[1]);
    if (!getPersonaName || !setPersonaName) {
        VerifyConsole::write(0.0f, "persona", "vtable slots 0/1 missing");
        return false;
    }

    // sanity + diagnostics: slot 0 must return the current persona (protects against an ABI
    // slot shift) - the readback also shows what Steam thinks the name is right now.
    // Echoed names MUST be sanitized: the echo goes through the console buffer, and ';'/NL
    // in a name would inject a second command (the "done; now" format bug of 2026-09-07).
    const char* current = getPersonaName(internal);
    if (!current || current[0] == '\0') {
        VerifyConsole::write(0.0f, "persona", "GetPersonaName empty - wrong interface/slot?");
        return false;
    }
    {
        char safe[64];
        chat_tools::sanitizeInto(current, safe, sizeof(safe));
        VerifyConsole::write(0.0f, "persona", "current persona: %s", safe[0] ? safe : "?");
    }

    const bool submitted = setPersonaName(internal, name);
    if (!submitted) {
        VerifyConsole::write(0.0f, "persona", "SetPersonaName REFUSED (handle 0 - rate limited or bad state)");
        return false;
    }
    chat_tools::sanitizeInto(name, chat_tools::personaRequested, sizeof(chat_tools::personaRequested));
    // Steam applies persona changes ASYNC and rate-limits them aggressively (attempts during
    // the last ~10+ minutes can all be dropped) - poll for 30s before declaring rejection
    chat_tools::personaPollsLeft = 30;
    VerifyConsole::write(0.0f, "persona", "SetPersonaName submitted - polling 30s...");
    return true;
}

// teammate color schema offset cache (game thread only)
inline bool teammateColorOffsetResolved = false;
inline std::optional<std::int32_t> teammateColorOffset;

// The full kick/disconnect reason list: {ENetworkDisconnectReason code, display label}.
// Merged from the extracted ENetworkDisconnectReason protobuf (libengine2 0x2ae6c0) and the
// friend's verified Windows list (all pairs match 1:1). The dropdown defIndex = the CODE
// sent to the server - the picker doubles as the entry list (itemList popup mode).
inline constexpr cs2::ItemDefEntry kKickReasonEntries[] = {
    // -- the troll classics: server-side kick lines --
    {163, "VACNet: Abnormal Behavior", ""},
    {164, "Insecure Client", ""},
    {162, "Input Automation", ""},
    {154, "Competitive Cooldown", ""},
    {153, "Convicted Account", ""},
    {152, "Untrusted Account", ""},
    {150, "Team Killing", ""},
    {151, "TK Round Start", ""},
    {155, "Team Hurting", ""},
    {156, "Hostage Killing", ""},
    {157, "Voted Off", ""},
    {158, "Idle (AFK)", ""},
    {159, "Suicide", ""},
    {160, "No Steam Login", ""},
    {161, "No Steam Ticket", ""},
    // -- steam account states --
    {13, "Steam VAC Ban State", ""},
    {6, "Steam Banned", ""},
    {9, "Steam Logon Invalid", ""},
    {12, "Steam Auth Invalid", ""},
    {11, "Steam Auth Already Used", ""},
    {10, "Steam Auth Cancelled", ""},
    {7, "Steam In Use", ""},
    {8, "Steam Ticket", ""},
    {14, "Steam Logged In Elsewhere", ""},
    {15, "Steam VAC Check Timed Out", ""},
    {16, "Steam Dropped", ""},
    {17, "Steam Ownership", ""},
    {68, "Steam Deny Bad Anti-Cheat", ""},
    {67, "Steam Deny Misc", ""},
    {66, "Server Requires Steam", ""},
    // -- connection theatrics --
    {39, "Kicked (Console)", ""},
    {40, "Ban Added", ""},
    {41, "Kick + Ban Added", ""},
    {84, "Unusual Activity", ""},
    {44, "Pure Server Mismatch", ""},
    {3, "Disconnected By Server", ""},
    {2, "Disconnected By User", ""},
    {69, "Server Shutdown", ""},
    {62, "Client Consistency Fail", ""},
    {49, "Bad Server Password", ""},
    {51, "Connection Failure", ""},
    {29, "Timed Out", ""},
    {4, "Connection Lost", ""},
    {5, "Connection Overflow", ""},
    {26, "Reliable Overflow", ""},
    {27, "Bad Delta Tick", ""},
    {1, "Shutdown", ""},
    {30, "Disconnected", ""},
};
inline constexpr int kKickReasonCount = static_cast<int>(sizeof(kKickReasonEntries) / sizeof(kKickReasonEntries[0]));

// which buffer chatTemplateRow is editing
enum BufferKind { kNameBuffer = 0, kSpamBuffer = 1, kWheelBuffer = 2, kIntelBuffer = 3, kAnimatorBuffer = 4, kBufferKindCount };

// buffers: the menu edits these; contents mirror the sidecar files
constexpr std::size_t kBufferTextSize = 160; // multi-line persona names are long

struct BufferState {
    char text[kBufferTextSize] = "";
    bool loaded = false;
};
inline BufferState buffers[kBufferKindCount]{};

inline constexpr const char* kFileNames[kBufferKindCount] = {
    "/chat_name.txt",
    "/chat_spam.txt",
    "/chatwheel.txt",
    "/chat_intel.txt",
    "/name_animator.txt",
};



// The fake-ban persona, referenced by the preset list AND the Ban Theater (one named constant
// so the two can never drift apart).
inline constexpr const char* kFakeBanPersona = "{nl}Krypt0n disconnected [VAC banned from secure server]{nl}Krypt0n has been permanently banned from official servers.{nl}";

// Invisible U+2067 RTL isolates + homoglyph badge (V + GREEK ALPHA + LV + SMALL-CAP E): looks
// like the real [VALVe] decoration, evades every client-side badge/chat filter, fully networked.
inline constexpr const char* kBadgeTail = " \xE2\x81\xA7\xE2\x81\xA7[V\xCE\x91LV\xE1\xB4\xB1]";

// One-click persona names. {nl} blocks render as fake system-message lines under your
// [ALL] <name> : line; the "Server Message" recipes abuse that for canned announcements.
inline constexpr const char* const kNamePresets[] = {
    "cat Enjoyer \xE2\x81\xA7\xE2\x81\xA7[V\xCE\x91LV\xE1\xB4\xB1]",
    "s1mple \xE2\x81\xA7\xE2\x81\xA7[V\xCE\x91LV\xE1\xB4\xB1]",
    "Valve Employee \xE2\x81\xA7\xE2\x81\xA7[V\xCE\x91LV\xE1\xB4\xB1]",
    "VAC Live \xE2\x81\xA7\xE2\x81\xA7[V\xCE\x91LV\xE1\xB4\xB1]",
    "VAC Live [VALVe]",
    kFakeBanPersona,
    "\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B",
    "\xEF\xBC\xB6\xEF\xBC\xA1\xEF\xBC\xA3 \xEF\xBC\xAC\xEF\xBC\x89\xEF\xBC\x96\xEF\xBC\x85",
    "\xE2\x80\xAE" "desiw taht txet yna",
    "{nl}[Server] This server will restart in 10 seconds{nl}[Server] Please finish your round{nl}",
    "{nl}You have received a competitive cooldown{nl}Reason: Griefing{nl}Expires in: 7 days{nl}",
    "{nl}Vote: Kick cat Enjoyer? (yes){nl}Vote passed 9-1 (90%){nl}cat Enjoyer was kicked from the match{nl}",
    "{nl}[ADMIN] cat Enjoyer is now the server owner{nl}[ADMIN] Type !rules in chat{nl}",
    "{nl}GOTV: Connecting to tournament relay...{nl}GOTV: Now spectating cat Enjoyer{nl}",
    // --- long joke names (2026-09-07) ---
    "I'm not cheating my mom watches me play",
    "yes I bought this account from a guy on discord",
    "baiting is a legitimate strategy and I stand by it",
    "gg go next gg go next gg go next gg go next",
    // --- more VAC/CS system-message theater (2026-09-07) ---
    "{nl}Thank you for your report.{nl}The suspect has been banned from official CS2 servers.{nl}",
    "{nl}Overwatch: The reviewed case resulted in a conviction.{nl}Thank you for contributing to community safety.{nl}",
    "{nl}Competitive Skill Group Updated{nl}Legendary Eagle Master{nl}",
    "{nl}CS Rating Update{nl}24,351 \xE2\x86\x92 14,203 (-10,148){nl}Your performance was below expectations{nl}",
    "{nl}Your Trust Factor has been significantly impacted{nl}by your recent in-game behavior{nl}",
    "{nl}You have received a rare item drop!{nl}\xE2\x98\x85 Karambit | Fade (Factory New){nl}",
    "{nl}Disconnection detected...{nl}Attempting to reconnect to the match{nl}",
    "{nl}Your account has been trade banned{nl}Reason: Fraudulent activity detected{nl}",
};
inline constexpr int kNamePresetCount = static_cast<int>(sizeof(kNamePresets) / sizeof(kNamePresets[0]));

// menu -> game thread: text pending for the next APPLY (preset click or the APPLY button).
// Non-empty wins over the sidecar so one-click presets need no file IO on the game thread.
inline char pendingNameText[kBufferTextSize] = "";

// one-shot requests from the menu (present thread), consumed by run() on the game thread
inline std::atomic<int> pendingCloneFragger{0};
inline std::atomic<int> pendingBanTheater{0};

// Ban Theater sequence: fake-ban name goes live, TheaterDelay seconds later `retry` fires the
// REAL "X left the game" line - the disconnect that sells the illusion. 0 = idle.
inline int theaterTicksLeft = 0;

// first-run sidecar seeding latch (game thread only)
inline bool seeded = false;

// doppelganger suffix: two zero-width spaces appended to a cloned name - IDENTICAL on screen,
// a distinct userinfo value (no "name already taken" style collisions, two scoreboard rows)
inline constexpr const char* kDoppelgangerSuffix = "\xE2\x80\x8B\xE2\x80\x8B";

// Default sidecar contents, written ONLY when the file does not exist yet (never overwritten).
inline const char* kChatNamesScriptPack =
    "# Name Cycle / persona list - one name per line, '#' comments. {nl} = line break in chat.\n"
    "cat Enjoyer \xE2\x81\xA7\xE2\x81\xA7[V\xCE\x91LV\xE1\xB4\xB1]\n"
    "s1mple \xE2\x81\xA7\xE2\x81\xA7[V\xCE\x91LV\xE1\xB4\xB1]\n"
    "VAC Live \xE2\x81\xA7\xE2\x81\xA7[V\xCE\x91LV\xE1\xB4\xB1]\n"
    "\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B\xE2\x80\x8B\n"
    "{nl}Krypt0n disconnected [VAC banned from secure server]{nl}Krypt0n has been permanently banned from official servers.{nl}\n"
    "{nl}[Server] This server will restart in 10 seconds{nl}[Server] Please finish your round{nl}\n"
    "{nl}You have received a competitive cooldown{nl}Reason: Griefing{nl}Expires in: 7 days{nl}\n"
    "{nl}Vote: Kick cat Enjoyer? (yes){nl}Vote passed 9-1 (90%){nl}cat Enjoyer was kicked from the match{nl}\n"
    "{nl}[ADMIN] cat Enjoyer is now the server owner{nl}[ADMIN] Type !rules in chat{nl}\n"
    "{nl}GOTV: Connecting to tournament relay...{nl}GOTV: Now spectating cat Enjoyer{nl}\n";

// <configDir>/<fileName> generic path build (the name cycler's list file uses this directly)
template <typename HookContext>
[[nodiscard]] bool sidecarPathLike(HookContext& hookContext, char (&path)[512], const char* fileName) noexcept
{
    const auto& directoryPath = hookContext.configState().pathToConfigDirectory;
    if (!directoryPath)
        return false;
    const auto* dir = reinterpret_cast<const char*>(directoryPath.get());
    std::size_t length = 0;
    while (dir[length] != '\0' && length + 1 < sizeof(path) - 24)
        ++length;
    std::memcpy(path, dir, length);
    const auto fileLength = std::strlen(fileName);
    std::memcpy(path + length, fileName, fileLength + 1);
    return true;
}

// <configDir>/<file> - same resolution as Killsay's killsay.txt path
template <typename HookContext>
[[nodiscard]] bool sidecarPathFor(HookContext& hookContext, char (&path)[512], BufferKind kind) noexcept
{
    return sidecarPathLike(hookContext, path, kFileNames[kind]);
}

// One small read (the sidecars are tiny); returns bytes read, <= 0 on failure.
inline int readFileSmall(const char* path, char* buffer, int capacity) noexcept
{
    const int fd = LinuxPlatformApi::open(path, 0 /* O_RDONLY */);
    if (fd < 0)
        return -1;
    const auto readBytes = LinuxPlatformApi::pread(fd, buffer, capacity, 0);
    LinuxPlatformApi::close(fd);
    if (readBytes > 0)
        buffer[readBytes] = '\0';
    return static_cast<int>(readBytes);
}

// Writes `content` to <configDir>/<fileName> ONLY when that file does not exist yet - first-run
// seeding for the script packs, never clobbers the user's edits.
template <typename HookContext>
void seedSidecarIfMissing(HookContext& hookContext, const char* fileName, const char* content) noexcept
{
    char path[512];
    if (!sidecarPathLike(hookContext, path, fileName))
        return;
    const int probe = LinuxPlatformApi::open(path, 0 /* O_RDONLY */);
    if (probe >= 0) {
        LinuxPlatformApi::close(probe);
        return;
    }
    const int fd = LinuxPlatformApi::open(path, O_WRONLY | O_CREAT | O_TRUNC, 0666);
    if (fd < 0)
        return;
    static_cast<void>(LinuxPlatformApi::write(fd, content, std::strlen(content)));
    LinuxPlatformApi::close(fd);
}

// Reads the FIRST line of a sidecar into `out` (sanitized). Missing/empty/comment file -> false.
template <typename HookContext>
[[nodiscard]] bool readSidecar(HookContext& hookContext, BufferKind kind, char* out, std::size_t outCapacity) noexcept
{
    char path[512];
    if (!sidecarPathFor(hookContext, path, kind))
        return false;
    const int fd = LinuxPlatformApi::open(path, 0 /* O_RDONLY */);
    if (fd < 0)
        return false;
    char fileBuffer[512];
    const auto readBytes = LinuxPlatformApi::pread(fd, fileBuffer, sizeof(fileBuffer) - 1, 0);
    LinuxPlatformApi::close(fd);
    if (readBytes <= 0)
        return false;
    fileBuffer[readBytes] = '\0';
    std::size_t length = 0;
    while (length < static_cast<std::size_t>(readBytes) && fileBuffer[length] != '\n')
        ++length;
    fileBuffer[length] = '\0';
    if (length == 0 || fileBuffer[0] == '#')
        return false;
    return sanitizeInto(fileBuffer, out, outCapacity) != 0;
}

// MULTI-LINE sidecar helpers (the name cycler's chat_names.txt: one persona per line,
// '#' comments allowed - same style as killsay.txt). Returns the enabled-line count, 0 when
// missing/empty.
template <typename HookContext>
[[nodiscard]] int sidecarListCount(HookContext& hookContext, const char* fileName) noexcept
{
    char path[512];
    if (!sidecarPathLike(hookContext, path, fileName))
        return 0;
    char fileBuffer[4096];
    const auto readBytes = readFileSmall(path, fileBuffer, sizeof(fileBuffer) - 1);
    if (readBytes <= 0)
        return 0;
    int totalLines = 0;
    std::size_t offset = 0;
    while (offset < static_cast<std::size_t>(readBytes)) {
        std::size_t length = 0;
        while (offset + length < static_cast<std::size_t>(readBytes) && fileBuffer[offset + length] != '\n')
            ++length;
        fileBuffer[offset + length] = '\0';
        if (length > 0 && fileBuffer[offset] != '#')
            ++totalLines;
        offset += length + 1;
    }
    return totalLines;
}

// Reads enabled line `lineIndex` (0-based, comments/blanks skipped) into `out` (sanitized,
// {nl} converted). Returns false when the index is out of range.
template <typename HookContext>
[[nodiscard]] bool readSidecarListLine(HookContext& hookContext, const char* fileName, int lineIndex, char* out, std::size_t outCapacity) noexcept
{
    char path[512];
    if (!sidecarPathLike(hookContext, path, fileName))
        return false;
    char fileBuffer[4096];
    const auto readBytes = readFileSmall(path, fileBuffer, sizeof(fileBuffer) - 1);
    if (readBytes <= 0)
        return false;

    int enabled = -1;
    std::size_t offset = 0;
    while (offset < static_cast<std::size_t>(readBytes)) {
        std::size_t length = 0;
        while (offset + length < static_cast<std::size_t>(readBytes) && fileBuffer[offset + length] != '\n')
            ++length;
        fileBuffer[offset + length] = '\0';
        if (length > 0 && fileBuffer[offset] != '#') {
            if (++enabled == lineIndex) {
                return sanitizeInto(fileBuffer + offset, out, outCapacity) != 0;
            }
        }
        offset += length + 1;
    }
    return false;
}

} // namespace chat_tools

template <typename HookContext>
class ChatTools {
public:
    explicit ChatTools(HookContext& hookContext) noexcept
        : hookContext{hookContext}
    {
    }

    // Menu (present thread) buffer access - DiscordRpc buffer pattern. The lazy sidecar load
    // happens on the game thread (ensureBuffersLoaded); until then the menu may show an empty
    // field for one frame, harmless.
    static char* buffer(int kind) noexcept
    {
        return chat_tools::buffers[kind].text;
    }

    // Flushes a buffer to its sidecar. Call through ui_config::withContext so the config dir
    // is resolvable (present-thread file IO, same as DiscordRpc::saveTemplates).
    template <int Kind>
    void saveBufferToFile() noexcept
    {
        static_assert(Kind >= 0 && Kind < chat_tools::kBufferKindCount);
        char path[512];
        if (!chat_tools::sidecarPathFor(hookContext, path, static_cast<chat_tools::BufferKind>(Kind)))
            return;
        const int fd = LinuxPlatformApi::open(path, O_WRONLY | O_CREAT | O_TRUNC, 0666);
        if (fd < 0)
            return;
        char sanitized[chat_tools::kBufferTextSize];
        const auto length = chat_tools::sanitizeInto(chat_tools::buffers[Kind].text, sanitized, sizeof(sanitized) - 1);
        sanitized[length] = '\n';
        static_cast<void>(LinuxPlatformApi::write(fd, sanitized, length + 1));
        LinuxPlatformApi::close(fd);
    }

    // Lazily pulls the sidecars into the menu buffers (game thread, once per buffer).
    void ensureBuffersLoaded() noexcept
    {
        for (int kind = 0; kind < chat_tools::kBufferKindCount; ++kind) {
            auto& state = chat_tools::buffers[kind];
            if (!state.loaded) {
                state.loaded = true;
                if (!readSidecar(hookContext, static_cast<chat_tools::BufferKind>(kind), state.text, sizeof(state.text)))
                    state.text[0] = '\0';
            }
        }
    }

    // Game thread ticker - CreateMove AND FrameStageNotify 6 (menu included). The parity gate
    // lets exactly one of the two per-frame callers drive the cadence; the subsystem states
    // below are namespace statics shared by both callers.
    void run() noexcept
    {
        CrashLogger::trace(0x310); // 0x310 entry / 0x311 exit (game thread)
        ensureBuffersLoaded();
        seedScriptPacks();

        if (chat_tools::callerParity.fetch_add(1, std::memory_order_relaxed) % 2 != 0) {
            CrashLogger::trace(0x311);
            return; // second caller of this frame - the first one already ticked the cadence
        }

        if (chat_tools::pendingNameApply.exchange(0, std::memory_order_acq_rel) != 0)
            applyFakeName();

        if (chat_tools::pendingCloneFragger.exchange(0, std::memory_order_acq_rel) != 0)
            cloneTopFragger();

        // the theater owns the name while it runs - spam/cycler would break the illusion
        const bool theaterActive = runBanTheater(chat_tools::pendingBanTheater.exchange(0, std::memory_order_acq_rel) != 0);

        runIntel();
        runPersonaPoll();

        if (!theaterActive) {
            runSpam();
            runNameCycle();
        }
        runHudColorCycle();
        runWheel();
        runLiveBadge();
        runFakeKick();
        CrashLogger::trace(0x311);
    }

    // Killstreak radio: escalates chatwheel voice lines on kill streaks. Wired from the
    // FireEventClientSide hook (EntryPoints) - the same dispatch Killsay hangs off.
    void onFireEventClientSide(cs2::IGameEvent* event) noexcept
    {
        if (!event)
            return;
        if (!GET_CONFIG_VAR(chat_vars::StreakRadioEnabled)) {
            chat_tools::streak = 0;
            return;
        }
        if (!game_events::is(event, "player_death"))
            return;
        CrashLogger::trace(0x320); // player_death reached the streak handler

        if (game_events::localPlayerIsAttacker(hookContext, event)) {
            ++chat_tools::streak;
            const char* line = nullptr;
            if (chat_tools::streak == 3)
                line = "Nice shot!";
            else if (chat_tools::streak == 5)
                line = "Excellent!";
            else if (chat_tools::streak == 8)
                line = "Everybody, get in here!";
            else if (chat_tools::streak == 12)
                line = "PEEK ME AGAIN I DARE YOU";
            if (line)
                sendWheel(line);
            return;
        }

        // our own death (or any death that is not our kill with us as victim) resets the streak
        if (game_events::localPlayerIsSlot(hookContext, game_events::entityForKey(event, "userid")))
            chat_tools::streak = 0;
    }

private:
    // First-run sidecar seeding (game thread, once per session).
    void seedScriptPacks() noexcept
    {
        if (chat_tools::seeded)
            return;
        chat_tools::seeded = true;
        chat_tools::seedSidecarIfMissing(hookContext, "/chat_name.txt",
            "VAC Live \xE2\x81\xA7\xE2\x81\xA7[V\xCE\x91LV\xE1\xB4\xB1]\n");
        chat_tools::seedSidecarIfMissing(hookContext, "/chat_spam.txt", "gg go next\n");
        chat_tools::seedSidecarIfMissing(hookContext, "/chatwheel.txt", "playerchatwheel CW.GoGoGo test\n");
        chat_tools::seedSidecarIfMissing(hookContext, chat_tools::kNamesListFile, chat_tools::kChatNamesScriptPack);
        chat_tools::seedSidecarIfMissing(hookContext, "/chat_intel.txt",
            "Last enemy: B tunnels, low HP{nl}[Server] Intel packet delivered\n");
        chat_tools::seedSidecarIfMissing(hookContext, "/name_animator.txt", "name animator");
    }

    // #4 doppelganger: mirror the current top-fragger's name plus an invisible suffix - two
    // IDENTICAL rows on every scoreboard, two indistinguishable chat names, one real person.
    void cloneTopFragger() noexcept
    {
        const auto snap = player_list::snapshot();
        const player_list::Row* best = nullptr;
        for (int i = 0; i < snap.count; ++i) {
            const auto& row = snap.rows[i];
            if (row.isLocalPlayer || row.kills <= 0)
                continue;
            if (!best || row.kills > best->kills)
                best = &row;
        }
        if (!best) {
            VerifyConsole::write(30.0f, "chat", "clone: nobody else has kills yet (player list needs a live match)");
            return;
        }

        char clean[96];
        chat_tools::sanitizeInto(best->name, clean, sizeof(clean));
        if (clean[0] == '\0')
            return;

        char command[160]{"name "};
        std::size_t writeIndex = 5;
        const auto nameLength = std::strlen(clean);
        const auto suffixLength = std::strlen(chat_tools::kDoppelgangerSuffix);
        if (nameLength + suffixLength >= sizeof(command) - 5)
            return;
        std::memcpy(command + writeIndex, clean, nameLength);
        writeIndex += nameLength;
        std::memcpy(command + writeIndex, chat_tools::kDoppelgangerSuffix, suffixLength);
        writeIndex += suffixLength;
        command[writeIndex] = '\0';
        hookContext.template make<EngineCommandExecutor>().execute(command);
    }

    // #6 ban theater: stage 1 = the fake-ban persona goes live; stage 2 (TheaterDelay seconds
    // later) = `retry` - the server's own "X left the game" line lands right after the fake
    // ban lines, making the whole lobby believe the ban was real. Returns true while running
    // (the caller pauses the name cycler + spam so they cannot spoil it).
    [[nodiscard]] bool runBanTheater(bool requested) noexcept
    {
        if (requested) {
            char command[196]{"name \""};
            char clean[chat_tools::kBufferTextSize];
            const auto length = chat_tools::sanitizeInto(chat_tools::kFakeBanPersona, clean, sizeof(clean));
            if (length > 0 && length < sizeof(command) - 7) {
                std::memcpy(command + 6, clean, length + 1);
                const auto commandLength = std::strlen(command);
                command[commandLength] = '"';
                command[commandLength + 1] = '\0';
                hookContext.template make<EngineCommandExecutor>().execute(command);
                chat_tools::setSteamPersonaName(clean);
            }
            chat_tools::theaterTicksLeft = static_cast<int>(GET_CONFIG_VAR(chat_vars::TheaterDelay)) * 64;
            VerifyConsole::write(8.0f, "theater", "fake ban live - disconnecting in a moment");
        }
        // NOTE: neither `retry` nor `reconnect` are client console commands in CS2 (both
        // print "Unknown command" - reconnect is engine-side, handled only in server/host
        // contexts). `disconnect` exists and lands the theater: fake ban lines -> the real
        // "X left the game". The user rejoins manually (or a future session automates the
        // rejoin via the lobby flow).
        if (chat_tools::theaterTicksLeft > 0 && --chat_tools::theaterTicksLeft == 0)
            hookContext.template make<EngineCommandExecutor>().execute("disconnect");
        return chat_tools::theaterTicksLeft > 0;
    }

    // Shared senders (sanitization + console command shape live in exactly one place).
    void sendSay(const char* text) noexcept
    {
        char command[128]{"say "};
        std::memcpy(command + 4, text, std::strlen(text) + 1);
        hookContext.template make<EngineCommandExecutor>().execute(command);
    }

    // Radio: the wheel phrase table (extracted from the game's off_459F2C0). USER-CONFIRMED
    // working format: `playerchatwheel CW.GoGoGo test` printed "[CT] VAC BYPASS: Go go go!"
    // in chat AND played the voice for everyone (do NOT wrap in `cmd ` - that made it a
    // silent no-op). The DISPLAYED text comes from the CW.* name - the custom arg2 is not
    // shown; keep arg2 a single token for the server's 3-token check.
    struct WheelPhrase { const char* name; };
    static constexpr WheelPhrase kWheelPhrases[] = {
        {"CW.EcoRound"}, {"CW.SpendRound"}, {"CW.NeedDrop"}, {"CW.NeedPlan"},
        {"CW.NeedLeader"}, {"CW.GoGoGo"}, {"CW.OMW"}, {"CW.FollowMe"},
        {"CW.FollowingYou"}, {"CW.GoA"}, {"CW.GoB"}, {"CW.GoToLocMid"},
        {"CW.Regroup"}, {"CW.StickTogether"}, {"CW.SpreadOut"}, {"CW.TeamFallBack"},
        {"CW.HoldPosition"}, {"CW.NeedQuiet"}, {"CW.ImAttacking"}, {"CW.HeardNoise"},
        {"CW.SeesEnemy"},
    };

    // Resolves the user's line to the full networked command.

    void sendWheel(const char* cwName) noexcept
    {
        char command[96];
        const auto length = std::snprintf(command, sizeof(command), "playerchatwheel %s %s", cwName, cwName);
        if (length > 0)
            hookContext.template make<EngineCommandExecutor>().execute(command);
    }

    // Fake intel: while enabled, the persona becomes "Server [VALVe]" and the bound key sends
    // the chat_intel.txt line (2s throttle). Disabling re-applies the chat_name.txt persona.
    void runIntel() noexcept
    {
        if (!GET_CONFIG_VAR(chat_vars::IntelEnabled)) {
            if (chat_tools::intelWasEnabled) {
                chat_tools::intelWasEnabled = false;
                chat_tools::intelWasDown = false;
                chat_tools::pendingNameText[0] = '\0'; // fall back to the sidecar persona
                applyFakeName();
            }
            return;
        }
        if (!chat_tools::intelWasEnabled) {
            chat_tools::intelWasEnabled = true;
            std::snprintf(chat_tools::pendingNameText, chat_tools::kBufferTextSize, "%s", chat_tools::kServerPersona);
            chat_tools::pendingNameApply.store(1, std::memory_order_release);
        }

        if (chat_tools::intelSendCooldown > 0)
            --chat_tools::intelSendCooldown;

        const auto key = GET_CONFIG_VAR(chat_vars::IntelBind);
        const bool down = key != 0 && Bind::isDown(key);
        if (down && !chat_tools::intelWasDown && chat_tools::intelSendCooldown == 0) {
            char text[96];
            if (chat_tools::readSidecar(hookContext, chat_tools::kIntelBuffer, text, sizeof(text))) {
                sendSay(text);
                chat_tools::intelSendCooldown = 128; // 2s between intel drops
            }
        }
        chat_tools::intelWasDown = down;
    }

    // Networked half of the LIVE badge: when the spectator count grows (someone new is watching
    // us), announce it once (10s cooldown). The local pill is drawn by the menu's overlay pass.
    void runLiveBadge() noexcept
    {
        if (chat_tools::liveSayCooldown > 0)
            --chat_tools::liveSayCooldown;

        const auto snap = spectator_list::snapshot();
        const int count = snap.spectatingOthers ? 0 : snap.count; // only spectators OF US count
        if (count == chat_tools::lastSpectatorCount)
            return;

        if (GET_CONFIG_VAR(chat_vars::LiveBadgeEnabled) && count > chat_tools::lastSpectatorCount && count > 0
            && chat_tools::liveSayCooldown == 0) {
            char text[80];
            std::snprintf(text, sizeof(text), "\xF0\x9F\x94\xB4 LIVE - %d viewer(s) in stream", count);
            sendSay(text);
            chat_tools::liveSayCooldown = 640; // 10s
        }
        chat_tools::lastSpectatorCount = count;
    }

    // Fake kick: bound key arms a ~180-frame burst (one send per frame - the server only
    // latches the delayed-kick reason in a specific client-state window, the burst catches it).
    // Fake kick AUTO-RETRY: one key press arms a loop that waits across frame stages and
    // sends one attempt every ~3.5s (the server only latches the delayed-kick reason in a
    // specific client-state window - the loop keeps trying until it lands, no key spam).
    // 12 attempts max, then it disarms. A rare game-side crash exists in the incoming
    // message dispatch around the disconnect (null handler in their table, intermittent) -
    // the gentle cadence keeps it rare; dense bursts are gone entirely.
    // Persona poll: GetPersonaName is LOCAL-first - if Steam ACCEPTED the change it flips
    // within a moment; if it stayed old after the polls, Steam rejected/throttled it.
    void runPersonaPoll() noexcept
    {
        if (chat_tools::personaPollsLeft <= 0)
            return;
        static int pollDivider = 0;
        if (++pollDivider < 64) // once per second
            return;
        pollDivider = 0;
        --chat_tools::personaPollsLeft;

        if (!chat_tools::resolvePersonaSymbols())
            return;
        void* internal = *reinterpret_cast<void**>(reinterpret_cast<std::uintptr_t>(chat_tools::steamFriends) + 0x8);
        const auto vtable = *reinterpret_cast<void***>(internal);
        const auto getPersonaName = reinterpret_cast<chat_tools::GetPersonaNameFn>(vtable[0]);
        const char* now = getPersonaName(internal);
        if (now && chat_tools::equalsIgnoreCase(now, chat_tools::personaRequested)) {
            char safe[64];
            chat_tools::sanitizeInto(now, safe, sizeof(safe));
            VerifyConsole::write(0.0f, "persona", "APPLIED - Steam persona is now: %s", safe[0] ? safe : "?");
            chat_tools::personaPollsLeft = 0;

            // Re-assert the `name` convar AFTER the persona landed: applyFakeName sets it first,
            // but the GC/GC-persona sync clobbers it back to the OLD persona in the meantime -
            // so the server's userinfo (and every scoreboard) kept the stale name. Now that
            // Steam and the persona agree, the cvar set sticks and the userinfo update carries
            // the new name to the server mid-match.
            char command[164]{"name \""};
            const auto length = std::strlen(chat_tools::personaRequested);
            if (length < sizeof(command) - 7) {
                std::memcpy(command + 6, chat_tools::personaRequested, length);
                command[6 + length] = '"';
                command[7 + length] = '\0';
            hookContext.template make<EngineCommandExecutor>().execute(command);
            VerifyConsole::write(0.0f, "name", "re-asserting in-game name");

            // CS2 servers read the name at CONNECT - mid-match `name` changes do not propagate.
            // With NameForceReconnect, `retry` rejoins the last server so the new persona name
            // is picked up immediately (the same mechanic ban theater uses).
            if (GET_CONFIG_VAR(chat_vars::NameForceReconnect)) {
                VerifyConsole::write(0.0f, "name", "reconnecting so the server picks up the new name");
                hookContext.template make<EngineCommandExecutor>().execute("retry");
            }
            return;
        }
            return;
        }
        if (chat_tools::personaPollsLeft == 0)
            VerifyConsole::write(0.0f, "persona", "Steam did NOT apply in 30s - rate limit (wait 10+ min) or account restriction");
    }

    void runFakeKick() noexcept
    {
        const auto key = GET_CONFIG_VAR(chat_vars::KickKey);
        const bool down = key != 0 && Bind::isDown(key);
        if (down && !chat_tools::kickWasDown)
            chat_tools::kickAttemptsRemaining = 20;
        chat_tools::kickWasDown = down;

        if (chat_tools::kickAttemptsRemaining <= 0)
            return;
        if (chat_tools::kickSendCooldown > 0) {
            --chat_tools::kickSendCooldown;
            return;
        }
        chat_tools::kickSendCooldown = 256; // 4s between attempts (64tps)
        --chat_tools::kickAttemptsRemaining;

        chat_tools::sendInvalidSteamLogon(GET_CONFIG_VAR(chat_vars::KickReason));
    }

    // the `name` cvar flags patch happens once per session (see applyFakeName)
    inline static bool nameCvarFlagsPatched{false};

    void applyFakeName() noexcept
    {
        char text[144];
        if (chat_tools::pendingNameText[0] != '\0') {
            // one-click path (APPLY button / persona preset): the menu staged the text, no
            // file read needed
            chat_tools::sanitizeInto(chat_tools::pendingNameText, text, sizeof(text));
            chat_tools::pendingNameText[0] = '\0';
        } else if (!chat_tools::readSidecar(hookContext, chat_tools::kNameBuffer, text, sizeof(text))) {
            return;
        }
        if (text[0] == '\0')
            return;
        // THE LIVE RENAME (friend's method, ported 2026-09-07): CS2 registers `name` without
        // FCVAR_USERINFO, so a plain `name "x"` never reaches the server - this was the reason
        // every earlier rename attempt "worked" on Steam but not in-game. Patch the cvar's
        // flags once (self-verified offset, see CvarSystem::patchUserInfoFlag), then `setinfo`
        // pushes the userinfo update: the name changes LIVE mid-match, the Steam persona stays
        // untouched, and there is no rate limit.
        if (!nameCvarFlagsPatched) {
            nameCvarFlagsPatched = hookContext.template make<CvarSystem>().patchUserInfoFlag("name");
            if (!nameCvarFlagsPatched) {
                VerifyConsole::write(0.0f, "name", "could not patch the name cvar flags (offset unverifiable)");
                return;
            }
            VerifyConsole::write(0.0f, "name", "name cvar flags patched (userinfo enabled)");
        }
        char command[164]{"setinfo name \""};
        std::memcpy(command + 14, text, std::strlen(text) + 1);
        const auto length = std::strlen(command);
        command[length] = '"';
        command[length + 1] = '\0';
        VerifyConsole::write(6.0f, "name", "applying fake name (live)");
        hookContext.template make<EngineCommandExecutor>().execute(command);

        // OPTIONAL persistence: the setinfo rename is session-only (a reconnect re-reads the
        // Steam persona). With Force Reconnect on, ALSO submit the Steam persona (rate-limited
        // ~once per 10 min - the poll + `retry` flow below handles the rest).
        if (GET_CONFIG_VAR(chat_vars::NameForceReconnect))
            chat_tools::setSteamPersonaName(text);
    }

    void runSpam() noexcept
    {
        if (!GET_CONFIG_VAR(chat_vars::SpamEnabled)) {
            chat_tools::spamTicksLeft = 0;
            chat_tools::spamLinesLeft = 0;
            chat_tools::spamCooldownLeft = 0;
            return;
        }
        if (chat_tools::spamCooldownLeft > 0) {
            --chat_tools::spamCooldownLeft;
            return;
        }
        if (chat_tools::spamTicksLeft > 0) {
            --chat_tools::spamTicksLeft;
            return;
        }
        if (chat_tools::spamLinesLeft == 0)
            chat_tools::spamLinesLeft = GET_CONFIG_VAR(chat_vars::SpamCount);

        char text[96];
        if (!readSidecar(hookContext, chat_tools::kSpamBuffer, text, sizeof(text)))
            return;
        char command[128]{"say "};
        std::memcpy(command + 4, text, std::strlen(text) + 1);
        hookContext.template make<EngineCommandExecutor>().execute(command);

        --chat_tools::spamLinesLeft;
        if (chat_tools::spamLinesLeft == 0)
            chat_tools::spamCooldownLeft = 192; // 3s of rest between bursts (spam-kick safety)
        else
            chat_tools::spamTicksLeft = static_cast<int>(GET_CONFIG_VAR(chat_vars::SpamInterval)) * 6; // 100ms units -> 64tps ticks
    }

    void runWheel() noexcept
    {
        if (!GET_CONFIG_VAR(chat_vars::WheelEnabled)) {
            chat_tools::wheelTicksLeft = 0;
            return;
        }
        if (chat_tools::wheelTicksLeft > 0) {
            --chat_tools::wheelTicksLeft;
            return;
        }
        const auto phraseIndex = static_cast<int>(GET_CONFIG_VAR(chat_vars::RadioPhrase));
        if (phraseIndex < 0 || phraseIndex >= chat_tools::kRadioPhraseCount)
            return;
        sendWheel(chat_tools::kRadioPhrases[phraseIndex].cwName);
        chat_tools::wheelTicksLeft = static_cast<int>(GET_CONFIG_VAR(chat_vars::WheelInterval)) * 6;
    }

    void runNameCycle() noexcept
    {
        if (!GET_CONFIG_VAR(chat_vars::NameCycleEnabled)) {
            chat_tools::cycleTicksLeft = 0;
            chat_tools::cycleIndex = 0;
            chat_tools::cycleCount = 0;
            return;
        }
        if (chat_tools::cycleTicksLeft > 0) {
            --chat_tools::cycleTicksLeft;
            return;
        }
        if (chat_tools::cycleCount == 0)
            chat_tools::cycleCount = chat_tools::sidecarListCount(hookContext, chat_tools::kNamesListFile);
        if (chat_tools::cycleCount == 0)
            return;
        if (chat_tools::cycleIndex >= chat_tools::cycleCount)
            chat_tools::cycleIndex = 0;

        char text[chat_tools::kBufferTextSize];
        if (!chat_tools::readSidecarListLine(hookContext, chat_tools::kNamesListFile, chat_tools::cycleIndex, text, sizeof(text))) {
            chat_tools::cycleCount = 0; // file shrank / line vanished - recount next tick
            return;
        }
        ++chat_tools::cycleIndex;

        if (text[0] == '\0')
            return;
        char command[184]{"name \""};
        std::memcpy(command + 6, text, std::strlen(text) + 1);
        const auto length = std::strlen(command);
        command[length] = '"';
        command[length + 1] = '\0';
        hookContext.template make<EngineCommandExecutor>().execute(command);
        chat_tools::cycleTicksLeft = static_cast<int>(GET_CONFIG_VAR(chat_vars::NameCycleInterval)) * 64; // seconds -> 64tps ticks
    }

    // Cycles the LOBBY PREFERRED COLOR via `cl_color 0..4` ("Preferred teammate color",
    // FCVAR_USERINFO). PROVEN working by the user — the party data builder (libclient
    // sub_1EF9AF0) reads the cl_color value LIVE into the GC payload, so every set updates
    // the party ring. (The cl_teammate_color_N commands are unrelated no-ops; do not use.)
    void runHudColorCycle() noexcept
    {
        if (!GET_CONFIG_VAR(chat_vars::HudColorCycle)) {
            chat_tools::colorTicksLeft = 0;
            chat_tools::colorIndex = 0;
            return;
        }
        if (chat_tools::colorTicksLeft > 0) {
            --chat_tools::colorTicksLeft;
            return;
        }

        char command[24];
        const auto length = std::snprintf(command, sizeof(command), "cl_color %d", static_cast<int>(chat_tools::colorIndex));
        if (length > 0)
            hookContext.template make<EngineCommandExecutor>().execute(command);
        chat_tools::colorIndex = (chat_tools::colorIndex + 1) % 5; // cl_color 0..4 (yellow/purple/green/blue/olive)
        const int speed = GET_CONFIG_VAR(chat_vars::HudColorCycleSpeed) < 1 ? 1 : GET_CONFIG_VAR(chat_vars::HudColorCycleSpeed);
        chat_tools::colorTicksLeft = 64 / speed - 1;
        if (chat_tools::colorTicksLeft < 0)
            chat_tools::colorTicksLeft = 0;
    }

    HookContext& hookContext;
};
