








#pragma once

#include <cstdint>

namespace cs2
{

struct ItemDefEntry {
    std::uint16_t defIndex;
    const char* name;
    const char* model; 
};

inline constexpr ItemDefEntry kCaseItems[] = {
    {4089, "Chroma 2 Case", ""},
    {4233, "Chroma 3 Case", ""},
    {4061, "Chroma Case", ""},
    {4471, "Clutch Case", ""},
    {4669, "CS20 Case", ""},
    {4001, "CS:GO Weapon Case", ""},
    {4004, "CS:GO Weapon Case 2", ""},
    {4010, "CS:GO Weapon Case 3", ""},
    {4548, "Danger Zone Case", ""},
    {4818, "Dreams & Nightmares Case", ""},
    {4002, "eSports 2013 Case", ""},
    {4005, "eSports 2013 Winter Case", ""},
    {4019, "eSports 2014 Summer Case", ""},
    {4091, "Falchion Case", ""},
    {7007, "Fever Case", ""},
    {4698, "Fracture Case", ""},
    {7003, "Gallery Case", ""},
    {4281, "Gamma 2 Case", ""},
    {4236, "Gamma Case", ""},
    {4288, "Glove Case", ""},
    {4482, "Horizon Case", ""},
    {4017, "Huntsman Weapon Case", ""},
    {4904, "Kilowatt Case", ""},
    {4003, "Operation Bravo Case", ""},
    {4018, "Operation Breakout Weapon Case", ""},
    {4717, "Operation Broken Fang Case", ""},
    {4352, "Operation Hydra Case", ""},
    {4011, "Operation Phoenix Weapon Case", ""},
    {4790, "Operation Riptide Case", ""},
    {4029, "Operation Vanguard Weapon Case", ""},
    {4187, "Operation Wildfire Case", ""},
    {4695, "Prisma 2 Case", ""},
    {4598, "Prisma Case", ""},
    {4846, "Recoil Case", ""},
    {4880, "Revolution Case", ""},
    {4186, "Revolver Case", ""},
    {4138, "Shadow Case", ""},
    {4620, "Shattered Web Case", ""},
    {4747, "Snakebite Case", ""},
    {4403, "Spectrum 2 Case", ""},
    {4351, "Spectrum Case", ""},
    {4009, "Winter Offensive Weapon Case", ""},
};

inline constexpr ItemDefEntry kKeyItems[] = {
    {30092, "Anubis Collection Workshop Contributor", ""},
    {1325, "Chroma 2 Case Key", ""},
    {1347, "Chroma 3 Case Key", ""},
    {1323, "Chroma Case Key", ""},
    {1373, "Clutch Case Key", ""},
    {1304, "Community Sticker Capsule 1 Key", ""},
    {1308, "Community Sticker Capsule 1 Key", ""},
    {1385, "CS20 Case Key", ""},
    {1212, "CS:GO Capsule Key", ""},
    {1203, "CS:GO Case Key", ""},
    {1375, "Danger Zone Case Key", ""},
    {1391, "Dreams & Nightmares Case Key", ""},
    {30050, "Dreams & Nightmares Contest Winner", ""},
    {1204, "eSports Key", ""},
    {1330, "Falchion Case Key", ""},
    {7008, "Fever Case Key", ""},
    {1387, "Fracture Case Key", ""},
    {7002, "Gallery Case Key", ""},
    {1351, "Gamma 2 Case Key", ""},
    {1350, "Gamma Case Key", ""},
    {1356, "Glove Case Key", ""},
    {1374, "Horizon Case Key", ""},
    {1305, "Huntsman Case Key", ""},
    {1307, "Huntsman Case Key", ""},
    {1394, "Kilowatt Case Key", ""},
    {1309, "Operation Breakout Case Key", ""},
    {1310, "Operation Breakout Case Key", ""},
    {1311, "Operation Breakout Case Key", ""},
    {1313, "Operation Breakout Case Key", ""},
    {1388, "Operation Broken Fang Case Key", ""},
    {1365, "Operation Hydra Case Key", ""},
    {1303, "Operation Phoenix Case Key", ""},
    {1390, "Operation Riptide Case Key", ""},
    {1322, "Operation Vanguard Case Key", ""},
    {7000, "Operation Wildfire Case Key", ""},
    {1386, "Prisma 2 Case Key", ""},
    {1383, "Prisma Case Key", ""},
    {1392, "Recoil Case Key", ""},
    {1393, "Revolution Case Key", ""},
    {1334, "Revolver Case Key", ""},
    {1333, "Shadow Case Key", ""},
    {1384, "Shattered Web Case Key", ""},
    {1389, "Snakebite Case Key", ""},
    {1366, "Spectrum 2 Case Key", ""},
    {1364, "Spectrum Case Key", ""},
    {30115, "Train 2025 Collection Workshop Contributor", ""},
    {1214, "Winter Offensive Case Key", ""},
};

inline constexpr ItemDefEntry kAgentItems[] = {
    {4619, "'Blueberries' Buckshot | NSWC SEAL", "agents/models/ctm_st6/ctm_st6_variantj.vmdl"},
    {4780, "'Medium Rare' Crasswater | Guerrilla Warfare", "agents/models/tm_jungle_raider/tm_jungle_raider_variantb2.vmdl"},
    {5504, "'The Doctor' Romanov | Sabre", "agents/models/tm_balkan/tm_balkan_varianth.vmdl"},
    {4680, "'Two Times' McCoy | TACP Cavalry", "agents/models/ctm_st6/ctm_st6_variantl.vmdl"},
    {5403, "'Two Times' McCoy | USAF TACP", "agents/models/ctm_st6/ctm_st6_variantm.vmdl"},
    {4712, "1st Lieutenant Farlow | SWAT", "agents/models/ctm_swat/ctm_swat_variantf.vmdl"},
    {5400, "3rd Commando Company | KSK", "agents/models/ctm_st6/ctm_st6_variantk.vmdl"},
    {4775, "Arno The Overgrown | Guerrilla Warfare", "agents/models/tm_jungle_raider/tm_jungle_raider_variantc.vmdl"},
    {4752, "Aspirant | Gendarmerie Nationale", "agents/models/ctm_gendarmerie/ctm_gendarmerie_variantd.vmdl"},
    {5601, "B Squadron Officer | SAS", "agents/models/ctm_sas/ctm_sas_variantf.vmdl"},
    {4714, "Bio-Haz Specialist | SWAT", "agents/models/ctm_swat/ctm_swat_varianth.vmdl"},
    {5503, "Blackwolf | Sabre", "agents/models/tm_balkan/tm_balkan_variantj.vmdl"},
    {4613, "Bloody Darryl The Strapped | The Professionals", "agents/models/tm_professional/tm_professional_varf5.vmdl"},
    {5402, "Buckshot | NSWC SEAL", "agents/models/ctm_st6/ctm_st6_variantg.vmdl"},
    {4751, "Chef d'Escadron Rouchard | Gendarmerie Nationale", "agents/models/ctm_gendarmerie/ctm_gendarmerie_variantc.vmdl"},
    {4750, "Chem-Haz Capitaine | Gendarmerie Nationale", "agents/models/ctm_gendarmerie/ctm_gendarmerie_variantb.vmdl"},
    {4716, "Chem-Haz Specialist | SWAT", "agents/models/ctm_swat/ctm_swat_variantj.vmdl"},
    {4757, "Cmdr. Davida 'Goggles' Fernandez | SEAL Frogman", "agents/models/ctm_diver/ctm_diver_varianta.vmdl"},
    {4771, "Cmdr. Frank 'Wet Sox' Baroud | SEAL Frogman", "agents/models/ctm_diver/ctm_diver_variantb.vmdl"},
    {4711, "Cmdr. Mae 'Dead Cold' Jamison | SWAT", "agents/models/ctm_swat/ctm_swat_variante.vmdl"},
    {4776, "Col. Mangos Dabisi | Guerrilla Warfare", "agents/models/tm_jungle_raider/tm_jungle_raider_variantd.vmdl"},
    {4774, "Crasswater The Forgotten | Guerrilla Warfare", "agents/models/tm_jungle_raider/tm_jungle_raider_variantb.vmdl"},
    {5602, "D Squadron Officer | NZSAS", "agents/models/ctm_sas/ctm_sas_variantg.vmdl"},
    {5037, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5058, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5059, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5060, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5061, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5062, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5063, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5064, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5065, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5066, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5067, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5068, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5069, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5070, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5071, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5072, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5073, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5074, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5075, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5076, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5077, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5078, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5079, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5080, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5081, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5082, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5083, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5084, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5085, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5086, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5087, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5097, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5300, "Default CT Agent", "agents/models/ctm_fbi/ctm_fbi.vmdl"},
    {5301, "Default CT Agent", "agents/models/ctm_fbi/ctm_fbi_varianta.vmdl"},
    {5302, "Default CT Agent", "agents/models/ctm_fbi/ctm_fbi_variantc.vmdl"},
    {5303, "Default CT Agent", "agents/models/ctm_fbi/ctm_fbi_variantd.vmdl"},
    {5304, "Default CT Agent", "agents/models/ctm_fbi/ctm_fbi_variante.vmdl"},
    {5600, "Default CT Agent", "agents/models/ctm_sas/ctm_sas.vmdl"},
    {5036, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5038, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5039, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5040, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5041, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5042, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5043, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5044, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5045, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5046, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5047, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5048, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5049, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5050, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5051, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5052, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5053, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5054, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5055, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5056, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5057, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5088, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5089, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5090, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5091, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5092, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5093, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5094, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5095, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5096, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5100, "Default T Agent", "agents/models/tm_leet/tm_leet_varianta.vmdl"},
    {5101, "Default T Agent", "agents/models/tm_leet/tm_leet_variantb.vmdl"},
    {5102, "Default T Agent", "agents/models/tm_leet/tm_leet_variantc.vmdl"},
    {5103, "Default T Agent", "agents/models/tm_leet/tm_leet_variantd.vmdl"},
    {5104, "Default T Agent", "agents/models/tm_leet/tm_leet_variante.vmdl"},
    {5200, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix.vmdl"},
    {5201, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix_varianta.vmdl"},
    {5202, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix_variantb.vmdl"},
    {5203, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix_variantc.vmdl"},
    {5204, "Default T Agent", "agents/models/tm_phoenix/tm_phoenix_variantd.vmdl"},
    {5500, "Dragomir | Sabre", "agents/models/tm_balkan/tm_balkan_variantf.vmdl"},
    {5505, "Dragomir | Sabre Footsoldier", "agents/models/tm_balkan/tm_balkan_variantl.vmdl"},
    {4773, "Elite Trapper Solman | Guerrilla Warfare", "agents/models/tm_jungle_raider/tm_jungle_raider_varianta.vmdl"},
    {5206, "Enforcer | Phoenix", "agents/models/tm_phoenix/tm_phoenix_variantf.vmdl"},
    {4730, "Getaway Sally | The Professionals", "agents/models/tm_professional/tm_professional_varj.vmdl"},
    {5105, "Ground Rebel  | Elite Crew", "agents/models/tm_leet/tm_leet_variantg.vmdl"},
    {4713, "John 'Van Healen' Kask | SWAT", "agents/models/ctm_swat/ctm_swat_variantg.vmdl"},
    {5109, "Jungle Rebel | Elite Crew", "agents/models/tm_leet/tm_leet_variantj.vmdl"},
    {4756, "Lieutenant 'Tree Hugger' Farlow | SWAT", "agents/models/ctm_swat/ctm_swat_variantk.vmdl"},
    {4772, "Lieutenant Rex Krikey | SEAL Frogman", "agents/models/ctm_diver/ctm_diver_variantc.vmdl"},
    {4728, "Little Kev | The Professionals", "agents/models/tm_professional/tm_professional_varh.vmdl"},
    {5404, "Lt. Commander Ricksaw | NSWC SEAL", "agents/models/ctm_st6/ctm_st6_varianti.vmdl"},
    {5306, "Markus Delrow | FBI HRT", "agents/models/ctm_fbi/ctm_fbi_variantg.vmdl"},
    {5501, "Maximus | Sabre", "agents/models/tm_balkan/tm_balkan_varianti.vmdl"},
    {5307, "Michael Syfers  | FBI Sniper", "agents/models/ctm_fbi/ctm_fbi_varianth.vmdl"},
    {4732, "Number K | The Professionals", "agents/models/tm_professional/tm_professional_vari.vmdl"},
    {4753, "Officer Jacques Beltram | Gendarmerie Nationale", "agents/models/ctm_gendarmerie/ctm_gendarmerie_variante.vmdl"},
    {5305, "Operator | FBI SWAT", "agents/models/ctm_fbi/ctm_fbi_variantf.vmdl"},
    {5106, "Osiris | Elite Crew", "agents/models/tm_leet/tm_leet_varianth.vmdl"},
    {5405, "Primeiro Tenente | Brazilian 1st Battalion", "agents/models/ctm_st6/ctm_st6_variantn.vmdl"},
    {5107, "Prof. Shahmat | Elite Crew", "agents/models/tm_leet/tm_leet_varianti.vmdl"},
    {5502, "Rezan The Ready | Sabre", "agents/models/tm_balkan/tm_balkan_variantg.vmdl"},
    {4718, "Rezan the Redshirt | Sabre", "agents/models/tm_balkan/tm_balkan_variantk.vmdl"},
    {4727, "Safecracker Voltzmann | The Professionals", "agents/models/tm_professional/tm_professional_varg.vmdl"},
    {5401, "Seal Team 6 Soldier | NSWC SEAL", "agents/models/ctm_st6/ctm_st6_variante.vmdl"},
    {4715, "Sergeant Bombson | SWAT", "agents/models/ctm_swat/ctm_swat_varianti.vmdl"},
    {4735, "Sir Bloody Darryl Royale | The Professionals", "agents/models/tm_professional/tm_professional_varf3.vmdl"},
    {4736, "Sir Bloody Loudmouth Darryl | The Professionals", "agents/models/tm_professional/tm_professional_varf4.vmdl"},
    {4726, "Sir Bloody Miami Darryl | The Professionals", "agents/models/tm_professional/tm_professional_varf.vmdl"},
    {4733, "Sir Bloody Silent Darryl | The Professionals", "agents/models/tm_professional/tm_professional_varf1.vmdl"},
    {4734, "Sir Bloody Skullhead Darryl | The Professionals", "agents/models/tm_professional/tm_professional_varf2.vmdl"},
    {5207, "Slingshot | Phoenix", "agents/models/tm_phoenix/tm_phoenix_variantg.vmdl"},
    {5205, "Soldier | Phoenix", "agents/models/tm_phoenix/tm_phoenix_varianth.vmdl"},
    {4749, "Sous-Lieutenant Medic | Gendarmerie Nationale", "agents/models/ctm_gendarmerie/ctm_gendarmerie_varianta.vmdl"},
    {5308, "Special Agent Ava | FBI", "agents/models/ctm_fbi/ctm_fbi_variantb.vmdl"},
    {5208, "Street Soldier | Phoenix", "agents/models/tm_phoenix/tm_phoenix_varianti.vmdl"},
    {5108, "The Elite Mr. Muhlik | Elite Crew", "agents/models/tm_leet/tm_leet_variantf.vmdl"},
    {4778, "Trapper Aggressor | Guerrilla Warfare", "agents/models/tm_jungle_raider/tm_jungle_raider_variantf.vmdl"},
    {4781, "Trapper | Guerrilla Warfare", "agents/models/tm_jungle_raider/tm_jungle_raider_variantf2.vmdl"},
    {4777, "Vypa Sista of the Revolution | Guerrilla Warfare", "agents/models/tm_jungle_raider/tm_jungle_raider_variante.vmdl"},
};

[[nodiscard]] inline const ItemDefEntry* itemDefById(const ItemDefEntry* list, int count, std::uint16_t defIndex) noexcept
{
    for (int i = 0; i < count; ++i) {
        if (list[i].defIndex == defIndex)
            return &list[i];
    }
    return nullptr;
}

}

