#pragma once

#include <Features/Combat/Aimbot/AimbotConfigVariables.h>
#include <Features/Combat/LegitAimbot/LegitAimbotConfigVariables.h>
#include <Features/Combat/Rcs/RcsConfigVariables.h>
#include <Features/Combat/SpreadCircleVis/SpreadCircleVisConfigVariables.h>
#include <Features/Radio/RadioConfigVariables.h>
#include <Features/Radio/SoundBoardConfigVariables.h>
#include <Features/Combat/SniperRifles/NoScopeInaccuracyVis/NoScopeInaccuracyVisConfigVariables.h>
#include <Features/Combat/Triggerbot/TriggerbotConfigVariables.h>
#include <Features/Game/BlockbotConfigVariables.h>
#include <Features/Game/BunnyhopConfigVariables.h>
#include <Features/Game/ChatToolsConfigVariables.h>
#include <Features/Game/CooldownRevealerConfigVariables.h>
#include <Features/Game/FakeCommendsConfigVariables.h>
#include <Features/Game/FakeLevelConfigVariables.h>
#include <Features/Game/FakePremierConfigVariables.h>
#include <Features/Game/GlitchGeneratorConfigVariables.h>
#include <Features/Visuals/ScoreboardEquipment/ScoreboardEquipmentConfigVariables.h>
#include <Features/Visuals/OffScreenArrows/OffScreenArrowsConfigVariables.h>
#include <Features/Visuals/BulletTracers/BulletTracersConfigVariables.h>
#include <Features/Visuals/KillEffects/KillEffectsConfigVariables.h>
#include <Features/Game/MovementConfigVariables.h>
#include <Features/Game/AutoPeekConfigVariables.h>
#include <Features/Game/RevealRadarConfigVariables.h>
#include <Features/Game/SpectateEnemiesConfigVariables.h>
#include <Features/Hud/SpectatorList/SpectatorListParams.h>
#include <Features/Game/FakePrimeConfigVariables.h>
#include <Features/Game/FvaConfigVariables.h>
#include <Features/Game/MatchAutoAcceptConfigVariables.h>
#include <Features/Game/HitLogConfigVariables.h>
#include <Features/Game/KillsayConfigVariables.h>
#include <Features/Game/NameAnimatorConfigVariables.h>
#include <Features/Game/NetLagConfigVariables.h>
#include <Features/Game/ServerLaggerConfigVariables.h>
#include <Features/Game/PlayerAnalyzer/PlayerAnalyzerConfigVariables.h>
#include <Features/Game/UserInfoFloodConfigVariables.h>
#include <Features/Game/ValveDsSpoofConfigVariables.h>
#include <Features/Game/PanicKeyConfigVariables.h>
#include <Features/Game/TeamDamageConfigVariables.h>
#include <Features/Hud/HudThemeColorConfigVariables.h>
#include <Features/Misc/DiscordRpcConfigVariables.h>
#include <Features/Game/AgentChangerConfigVariables.h>
#include <Features/Game/VoteRevealerConfigVariables.h>
#include <Features/Hud/BombPlantAlert/BombPlantAlertConfigVariables.h>
#include <Features/Hud/BindsList/BindsListConfigVariables.h>
#include <Features/Hud/BombTimer/BombTimerConfigVariables.h>
#include <Features/Hud/CombatStats/CombatStatsConfigVariables.h>
#include <Features/Hud/DefusingAlert/DefusingAlertConfigVariables.h>
#include <Features/Hud/KillfeedPreserver/KillfeedPreserverConfigVariables.h>
#include <Features/Hud/PostRoundTimer/PostRoundTimerConfigVariables.h>
#include <Features/Hud/StatusPanel/StatusPanelConfigVariables.h>
#include <Features/Hud/Watermark/WatermarkConfigVariables.h>
#include <Features/SkinChanger/SkinChangerConfigVariables.h>
#include <Features/Sound/HitSoundConfigVariables.h>
#include <Features/Sound/SoundVisualizationConfigVariables.h>
#include <Features/Sound/SpawnProtectionSoundConfigVariables.h>
#include <Features/Visuals/GrenadeTimers/GrenadeTimersConfigVariables.h>
#include <Features/Visuals/Hitmarker/HitmarkerConfigVariables.h>
#include <Features/Visuals/ModelGlow/ModelGlowConfigVariables.h>
#include <Features/Visuals/OutlineGlow/OutlineGlowConfigVariables.h>
#include <Features/Visuals/Chams/ChamsConfigVariables.h>
#include <Features/Visuals/PlayerInfoInWorld/PlayerInfoInWorldConfigVariables.h>
#include <Features/Visuals/PlayerList/PlayerListConfigVariables.h>
#include <Features/Visuals/Removals/RemovalsConfigVariables.h>
#include <Features/Visuals/ThirdPerson/ThirdPersonConfigVariables.h>
#include <Features/Visuals/ViewmodelMod/ViewmodelModConfigVariables.h>
#include <Features/Visuals/WorldColors/WorldColorsConfigVariables.h>
#include <UI/ImGui/Neverlose/MenuThemeConfigVariables.h>
#include <Features/Visuals/AnimationMods/AnimationModsConfigVariables.h>
#include <Utils/TypeList.h>

using ConfigVariableTypes = TypeList<
    BombTimerEnabled,
    watermark_vars::Enabled,
    DefusingAlertEnabled,
    KillfeedPreserverEnabled,
    PostRoundTimerEnabled,
    BombBeepSoundVisualizationEnabled,
    BombDefuseSoundVisualizationEnabled,
    HitSoundEnabled,
    radio_vars::Volume,
    SpawnProtectionSoundEnabled,
    HitLogEnabled,
    KillsayEnabled,
    TeamDamageTrackerEnabled,
    VoteRevealerEnabled,
    CooldownRevealerEnabled,
    BlockbotEnabled,
    BunnyhopEnabled,
    AutoStrafeEnabled,
    AutoStrafeMode,
    LegitStrafeStrength,
    LegitStrafeMouseThreshold,

    TestStraferEnabled,
    panic_vars::Bind,
    FakePrimeEnabled,
    FakeLevelEnabled,
    FakeLevelValue,
    MatchAutoAcceptEnabled,
    BombPlantSoundVisualizationEnabled,
    FootstepSoundVisualizationEnabled,
    WeaponReloadSoundVisualizationEnabled,
    WeaponScopeSoundVisualizationEnabled,
    model_glow_vars::Enabled,
    model_glow_vars::GlowPlayers,
    model_glow_vars::GlowOnlyEnemies,
    model_glow_vars::GlowWeapons,
    model_glow_vars::GlowDroppedBomb,
    model_glow_vars::GlowTickingBomb,
    model_glow_vars::GlowDefuseKits,
    model_glow_vars::GlowGrenadeProjectiles,
    model_glow_vars::AllyColor,
    model_glow_vars::EnemyColor,
    model_glow_vars::MolotovHue,
    model_glow_vars::FlashbangHue,
    model_glow_vars::HEGrenadeHue,
    model_glow_vars::SmokeGrenadeHue,
    model_glow_vars::DroppedBombHue,
    model_glow_vars::TickingBombHue,
    model_glow_vars::DefuseKitHue,
    outline_glow_vars::Enabled,
    outline_glow_vars::GlowDefuseKits,
    outline_glow_vars::GlowDroppedBomb,
    outline_glow_vars::GlowGrenadeProjectiles,
    outline_glow_vars::GlowHostages,
    outline_glow_vars::GlowPlayers,
    outline_glow_vars::GlowOnlyEnemies,
    outline_glow_vars::GlowTickingBomb,
    outline_glow_vars::GlowWeapons,
    outline_glow_vars::AllyColor,
    outline_glow_vars::EnemyColor,
    outline_glow_vars::MolotovHue,
    outline_glow_vars::FlashbangHue,
    outline_glow_vars::HEGrenadeHue,
    outline_glow_vars::SmokeGrenadeHue,
    outline_glow_vars::DroppedBombHue,
    outline_glow_vars::TickingBombHue,
    outline_glow_vars::DefuseKitHue,
    outline_glow_vars::HostageHue,
    player_info_vars::Enabled,
    player_info_vars::OnlyEnemies,
    player_info_vars::PlayerPositionArrowEnabled,
    player_info_vars::PlayerPositionArrowColorMode,
    player_info_vars::PlayerHealthEnabled,
    player_info_vars::PlayerHealthColorMode,
    player_info_vars::ActiveWeaponIconEnabled,
    player_info_vars::ActiveWeaponAmmoEnabled,
    player_info_vars::BombCarrierIconEnabled,
    player_info_vars::BombPlantIconEnabled,
    player_info_vars::BombDefuseIconEnabled,
    player_info_vars::HostagePickupIconEnabled,
    player_info_vars::HostageRescueIconEnabled,
    player_info_vars::BlindedIconEnabled,
    viewmodel_mod_vars::ModifyFov,
    viewmodel_mod_vars::ModifyPosition,
    viewmodel_mod_vars::OffsetX,
    viewmodel_mod_vars::OffsetY,
    viewmodel_mod_vars::OffsetZ,
    viewmodel_mod_vars::Pitch,
    viewmodel_mod_vars::Roll,
    viewmodel_mod_vars::Fov,
    no_scope_inaccuracy_vis_vars::Enabled,
    triggerbot_vars::Enabled,
    triggerbot_vars::HoldKey,
    triggerbot_vars::DelayMilliseconds,
    triggerbot_vars::DelayMillisecondsMax,
    triggerbot_vars::AccuracyCheck,
    triggerbot_vars::AccuracyRadius,
    triggerbot_vars::HeadOnly,
    triggerbot_vars::Hitchance,
    triggerbot_vars::MaxAccuracyOnly,
    triggerbot_vars::WallCheck,
    triggerbot_vars::Autowall,
    triggerbot_vars::AutowallMaxThickness,
    triggerbot_vars::SpreadCompensation,
    triggerbot_vars::SeededFire,
    triggerbot_vars::ThroughWalls,
    triggerbot_vars::MinDamage,
    triggerbot_vars::Backtrack,
    triggerbot_vars::BacktrackTicks,
    aimbot_vars::Enabled,
    aimbot_vars::TargetSelection,
    aimbot_vars::TargetLock,
    aimbot_vars::HitHead,
    aimbot_vars::HitChest,
    aimbot_vars::HitStomach,
    aimbot_vars::HitArms,
    aimbot_vars::HitLegs,
    aimbot_vars::SpreadCompensation,
    aimbot_vars::RecoilCompensation,
    aimbot_vars::ForceShot,
    aimbot_vars::ForceShotAir,
    aimbot_vars::Extrapolate,
    aimbot_vars::ExtrapolateTicks,
    aimbot_vars::BodyAim,
    aimbot_vars::Hitchance,
    aimbot_vars::MinDamage,
    aimbot_vars::Multipoint,
    aimbot_vars::Backtrack,
    aimbot_vars::BacktrackTicks,
    aimbot_vars::SpreadCircleFov,
    aimbot_vars::AutoStop,
    aimbot_vars::PointScale,
    aimbot_vars::DynamicPointscale,
    aimbot_vars::WallCheck,
    aimbot_vars::Autowall,
    aimbot_vars::SpreadGate,
    aimbot_vars::SeedFallback,
    aimbot_vars::ForceShotWait,
    aimbot_vars::ForceShotWaitTicks,
    movement_vars::EdgeJump,
    movement_vars::EdgeStop,
    movement_vars::SlowWalk,
    movement_vars::SlowWalkSpeed,
    movement_vars::FastLadder,
    movement_vars::JumpBug,
    movement_vars::Desubtick,
    autopeek_vars::Enabled,
    reveal_radar_vars::Enabled,
    chams_vars::HideEnemies,
    chams_vars::HideLocalPlayer,
    animation_mod_vars::Freeze,
    animation_mod_vars::DisableIK,
    animation_mod_vars::DisableRagdolls,
    animation_mod_vars::ModifyRagdollScale,
    animation_mod_vars::RagdollScale,
    animation_mod_vars::AnimateViewmodel,
    animation_mod_vars::ViewmodelSpinSpeed,
    animation_mod_vars::ViewmodelPitchSway,
    chams_vars::Enabled,
    chams_vars::EnemyColor,
    spectator_list_params::SpectatorListEnabled,
    PlayerListOffsetX,
    PlayerListOffsetY,
    legit_aimbot_vars::Mode,
    legit_aimbot_vars::VisibleAim,
    legit_aimbot_vars::AlwaysOn,
    legit_aimbot_vars::OnlyWhileFiring,
    legit_aimbot_vars::RequireMouseMovement,
    legit_aimbot_vars::IgnoreFlash,
    legit_aimbot_vars::RecoilCompensation,
    legit_aimbot_vars::Strength,
    legit_aimbot_vars::Deadzone,
    legit_aimbot_vars::MaxSpeed,
    legit_aimbot_vars::ReactionMs,
    legit_aimbot_vars::SwitchDelayMs,
    legit_aimbot_vars::SnapFov,
    legit_aimbot_vars::Enabled,
    legit_aimbot_vars::TargetSelection,
    legit_aimbot_vars::TargetLock,
    legit_aimbot_vars::WallCheck,
    legit_aimbot_vars::AimKey,
    legit_aimbot_vars::Fov,
    legit_aimbot_vars::Smooth,
    legit_aimbot_vars::DrawFov,
    legit_aimbot_vars::FovCircleColor,
    legit_aimbot_vars::HitHead,
    legit_aimbot_vars::HitChest,
    legit_aimbot_vars::HitStomach,
    legit_aimbot_vars::HitArms,
    legit_aimbot_vars::HitLegs,
    legit_aimbot_vars::SpreadCircleFov,
    spread_circle_vars::Enabled,
    spread_circle_vars::SpreadCircleColor,
    rcs_vars::Enabled,
    rcs_vars::Strength,
    BombPlantAlertEnabled,
    skin_changer_vars::KnifeModel,
    skin_changer_vars::KnifeSkin,
    skin_changer_vars::KnifeSkinWear,
    skin_changer_vars::KnifeSkinSeed,
    skin_changer_vars::StatTrakEnabled,
    skin_changer_vars::StatTrakValue,
#define NS_SKIN_CHANGER_F(base) skin_changer_vars::base, skin_changer_vars::base##Wear, skin_changer_vars::base##Seed,
    NS_SKIN_CHANGER_GUNS(NS_SKIN_CHANGER_F)
#undef NS_SKIN_CHANGER_F
    FvaEnabled,
    FvaZeroOriginSpoof,
    fva_vars::Substeps,
    FvaReseedChains,
    FvaChainOnFireOnly,
    ValveDsSpoofEnabled,
    FvaSilentShots,
    HitmarkerEnabled,
    HitmarkerLength,
    HitmarkerGap,
    HitmarkerTimeout,
    HitmarkerColor,
    ForceThirdPersonEnabled,
    ForceThirdPersonDistance,
    RemoveViewPunch,
    RemoveLegs,
    RemoveFlashOverlay,
    RemoveMenuAds,
    WorldColorsInfernoEnabled,
    MolotovColor,
    IncendiaryColor,
    WorldColorsLightsEnabled,
    WorldColorsLightColor,
    WorldColorsSkyEnabled,
    WorldColorsSkyColor,
    WorldColorsWorldEnabled,
    WorldColorsWorldColor,
    WorldColorsFogEnabled,
    WorldColorsFogColor,
    WorldColorsFogDensity,
    WorldColorsFogDistance,
    WorldColorsBloomEnabled,
    WorldColorsBloomStrength,
    WorldColorsSkyBrightness,
    PlayerListEnabled,
    MenuAccentColor,
    MenuButtonColor,
    MenuSliderColor,
    MenuGlowEnabled,
    MenuGlowColor,
    MenuGlowRainbow,
    MenuGlowSpeed,
    MenuGlowSize,
    MenuGlowDebug,
    watermark_vars::ShowFps,
    watermark_vars::ShowSpeed,
    watermark_vars::ShowPing,
    watermark_vars::ShowTeamDamage,
    watermark_vars::ShowClock,
    watermark_vars::OffsetX,
    watermark_vars::OffsetY,
    binds_list_vars::Enabled,
    grenade_timers_vars::Enabled,
    grenade_timers_vars::SmokeTimers,
    grenade_timers_vars::MolotovTimers,
    radio_vars::MicBroadcast,
    MenuStyleRainbow,
    discord_rpc_vars::Enabled,
    hud_theme_vars::Enabled,
    agent_changer_vars::AgentDef,
#define NS_MODEL_GLOW_COLOR(F) F(Flashbang) F(HEGrenade) F(SmokeGrenade) F(Molotov) F(DroppedBomb) F(TickingBomb) F(DefuseKit)
#define NS_OUTLINE_GLOW_COLOR(F) NS_MODEL_GLOW_COLOR(F) F(Hostage)
#define NS_GLOW_COLOR_VARS(sys, M) M(sys, Flashbang) M(sys, HEGrenade) M(sys, SmokeGrenade) M(sys, Molotov) M(sys, DroppedBomb) M(sys, TickingBomb) M(sys, DefuseKit)
    outline_glow_vars::FlashbangColor,
    outline_glow_vars::HEGrenadeColor,
    outline_glow_vars::SmokeGrenadeColor,
    outline_glow_vars::MolotovColor,
    outline_glow_vars::DroppedBombColor,
    outline_glow_vars::TickingBombColor,
    outline_glow_vars::DefuseKitColor,
    outline_glow_vars::HostageColor,
    model_glow_vars::FlashbangColor,
    model_glow_vars::HEGrenadeColor,
    model_glow_vars::SmokeGrenadeColor,
    model_glow_vars::MolotovColor,
    model_glow_vars::DroppedBombColor,
    model_glow_vars::TickingBombColor,
    model_glow_vars::DefuseKitColor,
    MenuReduceMotion,
    chat_vars::SpamEnabled,
    chat_vars::SpamCount,
    chat_vars::SpamInterval,
    chat_vars::WheelEnabled,
    chat_vars::RadioPhrase,
    chat_vars::WheelInterval,
    chat_vars::PingSpamEnabled,
    chat_vars::PingInterval,
    chat_vars::HudColorCycle,
    chat_vars::HudColorCycleSpeed,
    chat_vars::NameCycleEnabled,
    chat_vars::NameCycleInterval,
    chat_vars::TheaterDelay,
    chat_vars::IntelEnabled,
    chat_vars::IntelBind,
    chat_vars::StreakRadioEnabled,
    chat_vars::LiveBadgeEnabled,
    chat_vars::KickReason,
    chat_vars::KickKey,
    net_lag_vars::Enabled,
    net_lag_vars::FakelagAlways,
    net_lag_vars::ChokeKeyBind,
    net_lag_vars::ChokeTicks,
    net_lag_vars::BlipCount,
    net_lag_vars::DupCount,
    net_lag_vars::DelayEnabled,
    net_lag_vars::DelayMs,
    net_lag_vars::StatsEnabled,
    net_lag_vars::FloodBurstCount,
    net_lag_vars::FloodKeyBind,
    net_lag_vars::ConnlessFloodCount,
    net_lag_vars::ConnlessKeyBind,
    radio_vars::AirhornEnabled,
    radio_vars::AirhornFirstBlood,
    radio_vars::AirhornHeadshot,
    radio_vars::AirhornRoundWin,
    radio_vars::VoiceKeyBind,
    radio_vars::ShowNowPlaying,
    radio_vars::ShowMediaPlayers,
    radio_vars::NowPlayingOffsetX,
    radio_vars::NowPlayingOffsetY,
    soundboard_vars::ClipIndex,
    soundboard_vars::SoundKeyBind,
    soundboard_vars::VoiceFormat,
    chat_vars::NameForceReconnect,
    chat_vars::ClanTagEnabled,
    chat_vars::ClanTagAnimateEnabled,
    chat_vars::ClanTagAnimateMode,
    chat_vars::ClanTagAnimateSpeed,
    name_animator_vars::Enabled,
    name_animator_vars::Mode,
    name_animator_vars::Speed,
    name_animator_vars::DirectSend,
    combat_stats_vars::FeedLifetime,
    combat_stats_vars::FeedOffsetX,
    combat_stats_vars::FeedOffsetY,
    combat_stats_vars::CountersOffsetX,
    combat_stats_vars::CountersOffsetY,
    status_panel_vars::OffsetX,
    status_panel_vars::OffsetY,
    last_tick_vars::Enabled,
    last_tick_vars::DefuseKey,
    supertoss_vars::Enabled,
    userinfo_flood_vars::Enabled,
    userinfo_flood_vars::HeavyMode,
    userinfo_flood_vars::DirectMode,
    userinfo_flood_vars::FloodName,
    userinfo_flood_vars::FloodClutch,
    userinfo_flood_vars::FloodTeamColor,
    userinfo_flood_vars::FloodXhStyle,
    userinfo_flood_vars::FloodXhColor,
    userinfo_flood_vars::FloodXhSize,
    userinfo_flood_vars::FloodXhGap,
    userinfo_flood_vars::FloodXhThick,
    userinfo_flood_vars::FloodXhOutline,
    userinfo_flood_vars::FloodXhDot,
    userinfo_flood_vars::FloodXhAlpha,
    userinfo_flood_vars::FloodXhSniper,
    userinfo_flood_vars::FloodLoadout,
    userinfo_flood_vars::FloodTeamId,
    userinfo_flood_vars::FloodXhColorR,
    userinfo_flood_vars::FloodXhColorG,
    userinfo_flood_vars::FloodXhColorB,
    userinfo_flood_vars::SendsPerTick,
    userinfo_flood_vars::EveryTicks,
    server_lagger_vars::Enabled,    server_lagger_vars::MsgsPerBatch,
    server_lagger_vars::AudioKB,
    server_lagger_vars::Amount,
    server_lagger_vars::PayloadMode,
    server_lagger_vars::Preset,
    server_lagger_vars::DatagramMode,
    server_lagger_vars::LoopFreeze,
    server_lagger_vars::FreezeTicks,
    server_lagger_vars::AutoStop,
    server_lagger_vars::SlowRamp,
    server_lagger_vars::RampInterval,
    server_lagger_vars::LaggerKey,
    server_lagger_vars::NumPackets,
    server_lagger_vars::PulseMode,
    server_lagger_vars::PulseOn,
    server_lagger_vars::PulseOff,
    server_lagger_vars::MixMode,
    server_lagger_vars::PopulationScale,
    server_lagger_vars::Misattribute,
    analyzer_vars::Enabled,
    analyzer_vars::EspTag,
    analyzer_vars::SnapThreshold,
    analyzer_vars::VoiceProbe,
    spectate_vars::Enabled,
    binds_list_vars::OffsetX,
    binds_list_vars::OffsetY,
    server_lagger_vars::MeterEnabled,
    server_lagger_vars::MeterOffsetX,
    server_lagger_vars::MeterOffsetY,
    analyzer_vars::VoiceLog,
    analyzer_vars::Callout,
    analyzer_vars::CalloutTeamChat,
    analyzer_vars::CalloutThreshold,
    FakePremierEnabled,
    FakePremierScore,
    FakeCommendsEnabled,
    FakeCommendsFriendly,
    FakeCommendsTeaching,
    FakeCommendsLeader,
    FakeLevelXp,
    glitch_gen_vars::Style,
    glitch_gen_vars::Intensity,
    glitch_gen_vars::Preset,
    scoreboard_equipment_vars::Enabled,
    FakePremierWins,
    PremierWins,
    FakeWingmanEnabled,
    WingmanRank,
    OffScreenArrowsEnabled,
    OffScreenArrowsColor,
    OffScreenArrowsRadius,
    BulletTracersEnabled,
    KillEffectsEnabled,
    KillEffectsColor,
    OffScreenArrowsSize,
    KillEffectsScreenFlash
>;
